import { z } from 'zod';

export const ERROR_CODES = [
  'AUTH_REQUIRED',
  'PERMISSION_DENIED',
  'ETHICAL_WALL_BLOCKED',
  'AI_POLICY_BLOCKED',
  'DOCUMENT_LOCKED',
  'VALIDATION_FAILED',
  'UNSUPPORTED_FILE_TYPE',
  'EXTERNAL_LINK_EXPIRED',
  'TENANT_ISOLATION_VIOLATION',
] as const;

export type ErrorCode = (typeof ERROR_CODES)[number];

export const errorCodeSchema = z.enum(ERROR_CODES);

export interface ApiErrorResponse {
  code: ErrorCode;
  message?: string;
  reason?: string;
  requestId?: string;
}

export {
  auditActions,
  auditAnchorActions,
  dmsWorkAuditActions,
  fileSecurityAuditActions,
  auditMetadataKeys,
  isAuditAction,
  isAuditMetadataKey,
  r1AuditActions,
  r2DocumentAuditActions,
  r3SearchAuditActions,
  r4DlpAuditActions,
  r4EmailAuditActions,
  r5AuditConsoleActions,
  r5BreakGlassAuditActions,
  r6AiAuditActions,
  r6AiPrepAuditActions,
  r6AiFeedbackAuditActions,
  r6AiPolicyAuditActions,
  r7GraphAuditActions,
  r8ContractAuditActions,
  r9DdAuditActions,
  r10LitigationAuditActions,
  r11ExternalAuditActions,
  r12RecordsAuditActions,
  knowledgeBankAuditActions,
  r13EnterpriseAuditActions,
  r14ScaleLearningAuditActions,
  outlookAuditActions,
  type AuditAction,
  type AuditAnchorAction,
  type DmsWorkAuditAction,
  type FileSecurityAuditAction,
  type AuditMetadata,
  type AuditMetadataKey,
  type AuditMetadataValue,
  type R1AuditAction,
  type R2DocumentAuditAction,
  type R3SearchAuditAction,
  type R4DlpAuditAction,
  type R4EmailAuditAction,
  type R5AuditConsoleAction,
  type R5BreakGlassAuditAction,
  type R6AiAuditAction,
  type R6AiPrepAuditAction,
  type R6AiFeedbackAuditAction,
  type R6AiPolicyAuditAction,
  type R7GraphAuditAction,
  type R8ContractAuditAction,
  type R9DdAuditAction,
  type R10LitigationAuditAction,
  type R11ExternalAuditAction,
  type R12RecordsAuditAction,
  type KnowledgeBankAuditAction,
  type R13EnterpriseAuditAction,
  type R14ScaleLearningAuditAction,
  type OutlookAuditAction,
} from './types/audit';

export {
  canPromoteFileSecurityScan,
  canTransitionFileSecurityState,
  fileSecurityResultCodeSchema,
  fileSecurityResultCodes,
  fileSecurityStateSchema,
  fileSecurityStates,
  type FileSecurityResultCode,
  type FileSecurityState,
} from './file-security/file-security.types';

export {
  ingestionJobSchema,
  ingestionJobValidationErrorCode,
  ingestionParserProfiles,
  ingestionStorageAliases,
  MAX_INGESTION_EXPIRY_MS,
  MAX_INGESTION_OBJECT_BYTES,
  validateIngestionJob,
  type IngestionJob,
  type IngestionJobValidationResult,
} from './ingestion/ingestion-job';

export {
  createScaleAiGateReviewRequestSchema,
  createScaleCostSnapshotRequestSchema,
  createScaleEvalRunRequestSchema,
  createScaleLearningEventRequestSchema,
  createScaleMigrationDrillRequestSchema,
  createScalePerformanceRunRequestSchema,
  scaleAiGateDecisionSchema,
  scaleAiGateDecisions,
  scaleAiGateReviewListResponseSchema,
  scaleAiGateReviewSchema,
  scaleCostScopeSchema,
  scaleCostScopes,
  scaleCostSnapshotListResponseSchema,
  scaleCostSnapshotSchema,
  scaleEvalRunListResponseSchema,
  scaleEvalRunSchema,
  scaleEvalSuiteSchema,
  scaleEvalSuites,
  scaleLearningCategorySchema,
  scaleLearningCategories,
  scaleLearningEventListResponseSchema,
  scaleLearningEventSchema,
  scaleMigrationDrillListResponseSchema,
  scaleMigrationDrillSchema,
  scaleMigrationScopeSchema,
  scaleMigrationScopes,
  scalePerformanceRunListResponseSchema,
  scalePerformanceRunSchema,
  scaleReadinessSummarySchema,
  scaleRunStatusSchema,
  scaleRunStatuses,
  scaleScenarioSchema,
  scaleScenarios,
  type CreateScaleAiGateReviewRequestDto,
  type CreateScaleCostSnapshotRequestDto,
  type CreateScaleEvalRunRequestDto,
  type CreateScaleLearningEventRequestDto,
  type CreateScaleMigrationDrillRequestDto,
  type CreateScalePerformanceRunRequestDto,
  type ScaleAiGateReviewDto,
  type ScaleAiGateReviewListResponseDto,
  type ScaleCostSnapshotDto,
  type ScaleCostSnapshotListResponseDto,
  type ScaleEvalRunDto,
  type ScaleEvalRunListResponseDto,
  type ScaleLearningEventDto,
  type ScaleLearningEventListResponseDto,
  type ScaleMigrationDrillDto,
  type ScaleMigrationDrillListResponseDto,
  type ScalePerformanceRunDto,
  type ScalePerformanceRunListResponseDto,
  type ScaleReadinessSummaryDto,
} from './scale/scale-types';

export {
  createEnterpriseBackupSnapshotRequestSchema,
  createEnterpriseComplianceEvidenceRequestSchema,
  applyEnterpriseDmsMatterTemplateRequestSchema,
  enterpriseDmsConfigurationStatusSchema,
  enterpriseDmsConfigurationStatuses,
  enterpriseDmsDocumentSetSchema,
  enterpriseDmsMatterTemplateApplicationSchema,
  enterpriseDmsMatterTemplateListResponseSchema,
  enterpriseDmsMatterTemplateSchema,
  enterpriseDmsMetadataFieldSchema,
  enterpriseDmsMetadataFieldTypeSchema,
  enterpriseDmsMetadataFieldTypes,
  enterpriseDmsRefinerSourceSchema,
  enterpriseDmsRefinerSources,
  enterpriseApprovedDmsMatterTemplateCatalogSchema,
  enterpriseApprovedDmsMatterTemplateSchema,
  enterpriseApprovedDmsSearchRefinerCatalogSchema,
  enterpriseApprovedDmsSearchRefinerSchema,
  enterpriseApprovedDmsTaxonomyCatalogSchema,
  enterpriseApprovedDmsTaxonomySchema,
  enterpriseDmsSearchRefinerListResponseSchema,
  enterpriseDmsSearchRefinerFieldKeySchema,
  enterpriseDmsSearchRefinerFieldKeys,
  enterpriseDmsSearchRefinerSchema,
  enterpriseDmsSubtypeSchema,
  enterpriseDmsTaxonomyListResponseSchema,
  enterpriseDmsTaxonomySchema,
  createEnterpriseKeyReferenceRequestSchema,
  createEnterpriseSiemExportRequestSchema,
  createEnterpriseSsoProviderRequestSchema,
  enterpriseBackupScopeSchema,
  enterpriseBackupScopes,
  enterpriseBackupSnapshotListResponseSchema,
  enterpriseBackupSnapshotSchema,
  enterpriseBackupStatusSchema,
  enterpriseBackupStatuses,
  enterpriseComplianceEvidenceListResponseSchema,
  enterpriseComplianceEvidenceSchema,
  enterpriseComplianceFrameworkSchema,
  enterpriseComplianceFrameworks,
  enterpriseComplianceStatusSchema,
  enterpriseComplianceStatuses,
  enterpriseKeyProviderSchema,
  enterpriseKeyProviders,
  enterpriseKeyReferenceListResponseSchema,
  enterpriseKeyReferenceSchema,
  enterpriseKeyStatusSchema,
  enterpriseKeyStatuses,
  enterpriseReadinessSummarySchema,
  enterpriseSiemExportListResponseSchema,
  enterpriseSiemExportSchema,
  enterpriseSiemSinkTypeSchema,
  enterpriseSiemSinkTypes,
  enterpriseSsoEnforcementModeSchema,
  enterpriseSsoEnforcementModes,
  enterpriseSsoProviderListResponseSchema,
  enterpriseSsoProviderSchema,
  enterpriseSsoProviderStatusSchema,
  enterpriseSsoProviderStatuses,
  enterpriseSsoSpMetadataSchema,
  upsertEnterpriseDmsMatterTemplateRequestSchema,
  upsertEnterpriseDmsSearchRefinerRequestSchema,
  upsertEnterpriseDmsTaxonomyRequestSchema,
  type ApplyEnterpriseDmsMatterTemplateRequestDto,
  type CreateEnterpriseBackupSnapshotRequestDto,
  type CreateEnterpriseComplianceEvidenceRequestDto,
  type CreateEnterpriseKeyReferenceRequestDto,
  type CreateEnterpriseSiemExportRequestDto,
  type CreateEnterpriseSsoProviderRequestDto,
  type EnterpriseBackupSnapshotDto,
  type EnterpriseBackupSnapshotListResponseDto,
  type EnterpriseComplianceEvidenceDto,
  type EnterpriseComplianceEvidenceListResponseDto,
  type EnterpriseApprovedDmsMatterTemplateCatalogDto,
  type EnterpriseApprovedDmsMatterTemplateDto,
  type EnterpriseApprovedDmsSearchRefinerCatalogDto,
  type EnterpriseApprovedDmsSearchRefinerDto,
  type EnterpriseApprovedDmsTaxonomyCatalogDto,
  type EnterpriseApprovedDmsTaxonomyDto,
  type EnterpriseDmsDocumentSetDto,
  type EnterpriseDmsMatterTemplateApplicationDto,
  type EnterpriseDmsMatterTemplateDto,
  type EnterpriseDmsMatterTemplateListResponseDto,
  type EnterpriseDmsMetadataFieldDto,
  type EnterpriseDmsSearchRefinerDto,
  type EnterpriseDmsSearchRefinerFieldKey,
  type EnterpriseDmsSearchRefinerListResponseDto,
  type EnterpriseDmsSubtypeDto,
  type EnterpriseDmsTaxonomyDto,
  type EnterpriseDmsTaxonomyListResponseDto,
  type EnterpriseKeyReferenceDto,
  type EnterpriseKeyReferenceListResponseDto,
  type EnterpriseReadinessSummaryDto,
  type EnterpriseSiemExportDto,
  type EnterpriseSiemExportListResponseDto,
  type EnterpriseSsoProviderDto,
  type EnterpriseSsoProviderListResponseDto,
  type EnterpriseSsoSpMetadataDto,
  type UpsertEnterpriseDmsMatterTemplateRequestDto,
  type UpsertEnterpriseDmsSearchRefinerRequestDto,
  type UpsertEnterpriseDmsTaxonomyRequestDto,
} from './enterprise/enterprise-types';

export {
  createArchiveRequestSchema,
  createDisposalRequestSchema,
  createLegalHoldRequestSchema,
  createRetentionPolicyRequestSchema,
  disposalCertificateSchema,
  disposalReviewItemSchema,
  disposalReviewListResponseSchema,
  disposalRequestSchema,
  disposalRequestStatusSchema,
  disposalRequestStatuses,
  legalHoldListResponseSchema,
  legalHoldSchema,
  legalHoldScopeSchema,
  legalHoldScopes,
  legalHoldStatusSchema,
  legalHoldStatuses,
  recordsArchiveSchema,
  retryDisposalRequestSchema,
  retentionPolicyListResponseSchema,
  retentionPolicySchema,
  retentionPolicyStatusSchema,
  retentionPolicyStatuses,
  type CreateArchiveRequestDto,
  type CreateDisposalRequestDto,
  type CreateLegalHoldRequestDto,
  type CreateRetentionPolicyRequestDto,
  type DisposalCertificateDto,
  type DisposalReviewItemDto,
  type DisposalReviewListResponseDto,
  type DisposalRequestDto,
  type DisposalRequestStatus,
  type LegalHoldDto,
  type LegalHoldListResponseDto,
  type LegalHoldScope,
  type LegalHoldStatus,
  type RecordsArchiveDto,
  type RetryDisposalRequestDto,
  type RetentionPolicyDto,
  type RetentionPolicyListResponseDto,
} from './records/records-types';
export {
  dashboardAiPrepStatusSchema,
  dashboardIntegrationStatusSchema,
  dmsNotificationCenterResponseSchema,
  dmsNotificationItemSchema,
  dmsNotificationSourceSchema,
  dmsNotificationStatusSchema,
  dmsOperationalToneSchema,
  dmsAiPrepWorkItemKindSchema,
  dmsDocumentWorkItemKindSchema,
  dmsRecordsWorkItemKindSchema,
  dmsWorkflowWorkItemKindSchema,
  dmsWorkItemKindSchema,
  dmsWorkItemSourceSchema,
  dmsWorkItemStatusSchema,
  dmsWorkQueueAssigneeFilterSchema,
  dmsWorkQueueItemSchema,
  dmsWorkQueueQuerySchema,
  dmsWorkQueueResponseSchema,
  reassignWorkItemSchema,
  dashboardOverviewSchema,
  dashboardPolicyAlertSchema,
  dashboardRecentActivitySchema,
  dashboardRecentFileSchema,
  dashboardSectionIds,
  dashboardUsageStatsQuerySchema,
  dashboardUsageStatsResponseSchema,
  dashboardUsageStatsTopMatterSchema,
  type DashboardAiPrepStatusDto,
  type DashboardIntegrationStatusDto,
  type DashboardUsageStatsQueryDto,
  type DashboardUsageStatsResponseDto,
  type DashboardUsageStatsTopMatterDto,
  type DmsNotificationCenterResponseDto,
  type DmsNotificationItemDto,
  type DmsNotificationSource,
  type DmsNotificationStatus,
  type DmsOperationalTone,
  type DmsAiPrepWorkItemKind,
  type DmsDocumentWorkItemKind,
  type DmsRecordsWorkItemKind,
  type DmsWorkflowWorkItemKind,
  type DmsWorkItemKind,
  type DmsWorkItemSource,
  type DmsWorkItemStatus,
  type DmsWorkQueueAssigneeFilter,
  type DmsWorkQueueItemDto,
  type DmsWorkQueueQueryDto,
  type DmsWorkQueueResponseDto,
  type ReassignWorkItemDto,
  type DashboardOverviewDto,
  type DashboardPolicyAlertDto,
  type DashboardRecentActivityDto,
  type DashboardRecentFileDto,
  type DashboardSectionId,
} from './dashboard/dashboard-types';
export {
  createDdDataRoomMappingRequestSchema,
  createDdExportJobRequestSchema,
  createDdIssueRequestSchema,
  createDdNegotiationIssueExportRequestSchema,
  createDdReportExportRequestSchema,
  createDdRfiRequestSchema,
  createDdRiskRequestSchema,
  ddDataRoomMappingListResponseSchema,
  ddDataRoomMappingQuerySchema,
  ddDataRoomMappingSchema,
  ddIssueListResponseSchema,
  ddIssueQuerySchema,
  ddIssueSchema,
  ddIssueCitationRequiredReason,
  ddIssueSeveritySchema,
  ddIssueStatusSchema,
  ddIssueSeverities,
  ddIssueStatuses,
  ddMappingStatusSchema,
  ddMappingStatuses,
  ddPriorities,
  ddPrioritySchema,
  ddExportJobResponseSchema,
  ddExportTypeSchema,
  ddExportTypes,
  ddNegotiationIssueExportResponseSchema,
  ddReportExportResponseSchema,
  ddRfiCategories,
  ddRfiCategorySchema,
  ddRfiGapListResponseSchema,
  ddRfiGapQuerySchema,
  ddRfiListResponseSchema,
  ddRfiQuerySchema,
  ddRfiSchema,
  ddRfiStatusSchema,
  ddRfiStatuses,
  ddRiskCategories,
  ddRiskCategorySchema,
  ddRiskLikelihoodSchema,
  ddRiskLikelihoods,
  ddRiskListResponseSchema,
  ddRiskQuerySchema,
  ddRiskSchema,
  ddRiskStatusSchema,
  ddRiskStatuses,
  ddRfiTemplateInstantiateRequestSchema,
  ddRfiTemplateInstantiationResponseSchema,
  ddMappingSuggestionReviewResponseSchema,
  ddTraceabilityQuerySchema,
  ddTraceabilityResponseSchema,
  ddTraceabilityItemSchema,
  reviewDdMappingSuggestionRequestSchema,
  updateDdIssueRequestSchema,
  updateDdRfiRequestSchema,
  type CreateDdDataRoomMappingRequestDto,
  type CreateDdExportJobRequestDto,
  type CreateDdIssueRequestDto,
  type CreateDdNegotiationIssueExportRequestDto,
  type CreateDdReportExportRequestDto,
  type CreateDdRfiRequestDto,
  type CreateDdRiskRequestDto,
  type DdMappingSuggestionReviewResponseDto,
  type DdExportJobResponseDto,
  type DdExportType,
  type DdNegotiationIssueExportResponseDto,
  type DdReportExportResponseDto,
  type DdDataRoomMappingDto,
  type DdDataRoomMappingListResponseDto,
  type DdDataRoomMappingQueryDto,
  type DdIssueDto,
  type DdIssueListResponseDto,
  type DdIssueQueryDto,
  type DdIssueSeverity,
  type DdIssueStatus,
  type DdMappingStatus,
  type DdPriority,
  type DdRfiCategory,
  type DdRfiDto,
  type DdRfiGapListResponseDto,
  type DdRfiGapQueryDto,
  type DdRfiListResponseDto,
  type DdRfiQueryDto,
  type DdRfiStatus,
  type DdRfiTemplateInstantiateRequestDto,
  type DdRfiTemplateInstantiationResponseDto,
  type DdRiskCategory,
  type DdRiskDto,
  type DdRiskLikelihood,
  type DdRiskListResponseDto,
  type DdRiskQueryDto,
  type DdRiskStatus,
  type DdTraceabilityItemDto,
  type DdTraceabilityQueryDto,
  type DdTraceabilityResponseDto,
  type ReviewDdMappingSuggestionRequestDto,
  type UpdateDdIssueRequestDto,
  type UpdateDdRfiRequestDto,
} from './dd/dd-types';

export {
  createLitigationAiSuggestionRequestSchema,
  createLitigationEvidenceRequestSchema,
  createLitigationFactRequestSchema,
  createLitigationHearingRequestSchema,
  createLitigationIssueRequestSchema,
  createLitigationPleadingRequestSchema,
  litigationAdmittedStatusSchema,
  litigationAdmittedStatuses,
  litigationAiSuggestionKindSchema,
  litigationAiSuggestionKinds,
  litigationAiSuggestionListResponseSchema,
  litigationAiSuggestionQuerySchema,
  litigationAiSuggestionSchema,
  litigationAiSuggestionStatusSchema,
  litigationAiSuggestionStatuses,
  litigationCaseMapItemSchema,
  litigationCaseMapQuerySchema,
  litigationCaseMapResponseSchema,
  litigationCustodyStatusSchema,
  litigationCustodyStatuses,
  litigationEvidenceDirectionSchema,
  litigationEvidenceDirections,
  litigationEvidenceListResponseSchema,
  litigationEvidenceNextCodeQuerySchema,
  litigationEvidenceNextCodeResponseSchema,
  litigationEvidenceQuerySchema,
  litigationEvidenceSchema,
  litigationEvidenceTypeSchema,
  litigationEvidenceTypes,
  litigationFactListResponseSchema,
  litigationFactQuerySchema,
  litigationFactSchema,
  litigationFactCitationRequiredReason,
  litigationFactStatusSchema,
  litigationFactStatuses,
  litigationHearingListResponseSchema,
  litigationHearingQuerySchema,
  litigationHearingSchema,
  litigationHearingStatusSchema,
  litigationHearingStatuses,
  litigationHearingTypeSchema,
  litigationHearingTypes,
  litigationIssueListResponseSchema,
  litigationIssueQuerySchema,
  litigationIssueSchema,
  litigationIssueStatusSchema,
  litigationIssueStatuses,
  litigationIssueTypeSchema,
  litigationIssueTypes,
  litigationMaterialities,
  litigationMaterialitySchema,
  litigationPleadingListResponseSchema,
  litigationPleadingQuerySchema,
  litigationPleadingSchema,
  litigationPleadingStatusSchema,
  litigationPleadingStatuses,
  litigationPleadingTypeSchema,
  litigationPleadingTypes,
  updateLitigationFactRequestSchema,
  updateLitigationHearingRequestSchema,
  type CreateLitigationAiSuggestionRequestDto,
  type CreateLitigationEvidenceRequestDto,
  type CreateLitigationFactRequestDto,
  type CreateLitigationHearingRequestDto,
  type CreateLitigationIssueRequestDto,
  type CreateLitigationPleadingRequestDto,
  type LitigationAdmittedStatus,
  type LitigationAiSuggestionDto,
  type LitigationAiSuggestionKind,
  type LitigationAiSuggestionListResponseDto,
  type LitigationAiSuggestionQueryDto,
  type LitigationAiSuggestionStatus,
  type LitigationCaseMapItemDto,
  type LitigationCaseMapQueryDto,
  type LitigationCaseMapResponseDto,
  type LitigationCustodyStatus,
  type LitigationEvidenceDirection,
  type LitigationEvidenceDto,
  type LitigationEvidenceListResponseDto,
  type LitigationEvidenceNextCodeQueryDto,
  type LitigationEvidenceNextCodeResponseDto,
  type LitigationEvidenceQueryDto,
  type LitigationEvidenceType,
  type LitigationFactDto,
  type LitigationFactListResponseDto,
  type LitigationFactQueryDto,
  type LitigationFactStatus,
  type LitigationHearingDto,
  type LitigationHearingListResponseDto,
  type LitigationHearingQueryDto,
  type LitigationHearingStatus,
  type LitigationHearingType,
  type LitigationIssueDto,
  type LitigationIssueListResponseDto,
  type LitigationIssueQueryDto,
  type LitigationIssueStatus,
  type LitigationIssueType,
  type LitigationMateriality,
  type LitigationPleadingDto,
  type LitigationPleadingListResponseDto,
  type LitigationPleadingQueryDto,
  type LitigationPleadingStatus,
  type LitigationPleadingType,
  type UpdateLitigationFactRequestDto,
  type UpdateLitigationHearingRequestDto,
} from './litigation/litigation-types';

export {
  acceptExternalNdaRequestSchema,
  createExternalAnswerRequestSchema,
  createExternalLinkRequestSchema,
  createExternalQuestionRequestSchema,
  createExternalUserRequestSchema,
  createExternalWorkspaceRequestSchema,
  externalAccessManifestSchema,
  externalAccessStatusResponseSchema,
  externalAccessStatusSchema,
  externalAccessStatuses,
  externalDlpWarningStatusSchema,
  externalDlpWarningStatuses,
  externalDownloadTicketSchema,
  externalManagementWorkspaceListResponseSchema,
  externalManagementWorkspaceSchema,
  externalLinkCreatedResponseSchema,
  externalLinkSchema,
  externalLinkStatusSchema,
  externalLinkStatuses,
  externalNdaAcceptanceSchema,
  externalQaDirectionSchema,
  externalQaDirections,
  externalQaListResponseSchema,
  externalQaMessageStatusSchema,
  externalQaMessageStatuses,
  externalQaMessageSchema,
  externalQaReviewDecisionSchema,
  externalQaReviewDecisions,
  externalQaVisibilityScopeSchema,
  externalQaVisibilityScopes,
  externalUserSchema,
  externalUserStatusSchema,
  externalUserStatuses,
  externalWorkspaceSchema,
  externalWorkspaceStatusSchema,
  externalWorkspaceStatuses,
  listExternalWorkspacesQuerySchema,
  reviewExternalAnswerRequestSchema,
  type AcceptExternalNdaRequestDto,
  type CreateExternalAnswerRequestDto,
  type CreateExternalLinkRequestDto,
  type CreateExternalQuestionRequestDto,
  type CreateExternalUserRequestDto,
  type CreateExternalWorkspaceRequestDto,
  type ExternalAccessManifestDto,
  type ExternalAccessStatus,
  type ExternalAccessStatusResponseDto,
  type ExternalDlpWarningStatus,
  type ExternalDownloadTicketDto,
  type ExternalManagementWorkspaceDto,
  type ExternalManagementWorkspaceListResponseDto,
  type ExternalLinkCreatedResponseDto,
  type ExternalLinkDto,
  type ExternalLinkStatus,
  type ExternalNdaAcceptanceDto,
  type ExternalQaDirection,
  type ExternalQaListResponseDto,
  type ExternalQaMessageStatus,
  type ExternalQaMessageDto,
  type ExternalQaReviewDecision,
  type ExternalQaVisibilityScope,
  type ExternalUserDto,
  type ExternalUserStatus,
  type ExternalWorkspaceDto,
  type ExternalWorkspaceStatus,
  type ListExternalWorkspacesQueryDto,
  type ReviewExternalAnswerRequestDto,
} from './external/external-types';

export {
  aiModelRouteKeys,
  aiModelTiers,
  aiPolicyBlockReasonCodes,
  aiPolicyBlockedResponse,
  aiPolicyPurposes,
  type AiDocumentPolicyDecision,
  type AiDocumentPolicyExclusion,
  type AiModelRouteKey,
  type AiModelTier,
  type AiPolicyAuditResult,
  type AiPolicyBlockReasonCode,
  type AiPolicyBlockedResponse,
  type AiPolicyDecisionEffect,
  type AiPolicyDefaultEffect,
  type AiPolicyEvaluationRequest,
  type AiPolicyEvaluationResult,
  type AiPolicyPurpose,
  type AiPolicySchema,
} from './types/ai-policy';
export {
  breakGlassReasonCodes,
  breakGlassRequestStatuses,
  createBreakGlassRequestSchema,
  listBreakGlassRequestsQuerySchema,
  revokeBreakGlassRequestSchema,
  type BreakGlassReasonCode,
  type BreakGlassRequestListDto,
  type BreakGlassRequestDto,
  type BreakGlassRequestStatus,
  type CreateBreakGlassRequestDto,
  type ListBreakGlassRequestsQueryDto,
  type RevokeBreakGlassRequestDto,
} from './break-glass/break-glass.dto';

export {
  tenantStatuses,
  workspaceStatuses,
  type TenantId,
  type TenantStatus,
  type TenantSummary,
  type WorkspaceStatus,
} from './types/tenant';
export { userStatuses, type UserListDto, type UserStatus, type UserSummary } from './types/user';
export type { FileObjectDto } from './types/file-object';
export { buildSafeLabel, type DisplayFieldsDto } from './display/display-fields.dto';
export {
  documentConfidentialityLevelSchema,
  documentConfidentialityLevels,
  documentPrivilegeStatusSchema,
  documentPrivilegeStatuses,
  documentSourceSchema,
  documentSources,
  documentVersionRenditionTypeSchema,
  documentVersionRenditionTypes,
  documentVersionSignificanceSchema,
  documentVersionSignificances,
  documentExtractionMethods,
  documentExtractionStatuses,
  documentStatusSchema,
  documentStatuses,
  documentTypeSchema,
  documentTypes,
  listDocumentSortSchema,
  listDocumentSortValues,
  listDocumentsQuerySchema,
  type DocumentConfidentialityLevel,
  type DocumentDto,
  type DocumentExtractionMethod,
  type DocumentExtractionStatus,
  type DocumentListDto,
  type DocumentPrivilegeStatus,
  type DocumentSource,
  type DocumentStatus,
  type DocumentType,
  type DocumentVersionRenditionType,
  type DocumentVersionSignificance,
  type ListDocumentSort,
  type ListDocumentsQueryDto,
} from './types/document';
export {
  dlpBehaviorAlertListResponseSchema,
  dlpBehaviorAlertSchema,
  dlpBehaviorAlertStatusSchema,
  dlpBehaviorAlertStatuses,
  createDlpReviewRequestSchema,
  dlpAssessmentSourceTypes,
  dlpEgressPurposes,
  dlpFindingTypes,
  dlpReviewDecisions,
  dlpReviewReasonCodes,
  dlpReviewResponseSchema,
  dlpRestrictedFindingTypes,
  dlpRuleIds,
  dlpScanStates,
  dlpUnscannableReasonCodes,
  sf20DlpDefaultMaxFindings,
  sf20DlpMaxReviewDays,
  sf20DlpMaxScanCharacters,
  sf20DlpPolicyVersion,
  sf20DlpTotalFindingReviewThreshold,
  type CreateDlpReviewRequestDto,
  type DlpAssessmentSourceType,
  type DlpAssessmentSummary,
  type DlpBehaviorAlertDto,
  type DlpBehaviorAlertListResponseDto,
  type DlpBehaviorAlertStatus,
  type DlpDetection,
  type DlpEgressPurpose,
  type DlpFindingType,
  type DlpReviewDecision,
  type DlpReviewReasonCode,
  type DlpReviewResponseDto,
  type DlpRuleId,
  type DlpScanOptions,
  type DlpScanState,
  type DlpSensitiveDataScanResult,
  type DlpUnscannableReasonCode,
} from './dlp/dlp-types';
export {
  scanSensitiveData,
  scanSensitiveDataWithStatus,
  sensitiveDataRules,
  type SensitiveDataRule,
  type SensitiveDataScanOptions,
} from './dlp/sensitive-data-rules';
export {
  emailFailureReasonCodes,
  emailMatterSuggestionConfidenceBands,
  emailMatterWarningCodes,
  emailMatterSuggestionReasonCodes,
  emailMatterSuggestionQuerySchema,
  emailPrivilegeSuggestionReasonCodes,
  emailPrivilegeTagSuggestions,
  emailParticipantClasses,
  emailParserKinds,
  emailParseStatuses,
  emailSuggestionFeedbackActions,
  fileEmailToMatterSchema,
  undoEmailAutofileSchema,
  uploadEmailToMatterFieldsSchema,
  type EmailMatterSuggestionConfidenceBand,
  type EmailMatterFilingDto,
  type EmailMatterSuggestionDto,
  type EmailMatterSuggestionListDto,
  type EmailMatterSuggestionQueryDto,
  type EmailMatterSuggestionReasonCode,
  type EmailMatterWarningCode,
  type EmailParticipantClass,
  type EmailParticipantClassSummaryDto,
  type EmailPrivilegeSuggestionReasonCode,
  type EmailPrivilegeTagSuggestion,
  type EmailPrivilegeTagSuggestionDto,
  type EmailThreadGroupDto,
  type EmailThreadSummaryDto,
  type EmailTimelineDto,
  type EmailFailureReasonCode,
  type EmailMessageDto,
  type EmailParserKind,
  type EmailParseStatus,
  type EmailSuggestionFeedbackAction,
  type FileEmailToMatterDto,
  type UndoEmailAutofileDto,
  type UploadEmailToMatterFieldsDto,
  type UploadEmailToMatterResponseDto,
} from './email/email-types';
export {
  acquireOutlookGraphAttachmentSchema,
  cancelOutlookFilingRequestSchema,
  createOutlookDocumentInsertionSchema,
  createOutlookEmailFilingRequestSchema,
  createOutlookFolderMappingSchema,
  createOutlookSendFileRequestSchema,
  evaluateOutlookSendPolicySchema,
  matterSuggestionQuerySchema,
  matterSuggestionReasonCodes,
  outlookAddinSessionExchangeSchema,
  outlookAddinSessionStatuses,
  outlookAttachmentRefSchema,
  outlookAutofileDeniedReasonCodes,
  outlookAutofileJobStatuses,
  outlookDeniedReasonCodes,
  outlookDocumentInsertionDeniedReasonCodes,
  outlookDocumentInsertionModes,
  outlookDocumentInsertionStatuses,
  outlookDlpFindingRefSchema,
  outlookDlpScanFailureCodes,
  outlookDlpScanReportSchema,
  outlookDlpScanStatuses,
  outlookFolderMappingApprovalDecisions,
  outlookFolderMappingApprovalStatuses,
  outlookFolderMappingDeniedReasonCodes,
  outlookFolderMappingModes,
  outlookFilingRequestKinds,
  outlookFilingRequestStatuses,
  outlookGraphAttachmentAcquisitionStatuses,
  outlookHashSchema,
  outlookItemRefSchema,
  outlookMailboxBindingStatuses,
  outlookSendPolicyDecisions,
  outlookSendWarningReasonCodes,
  outlookSourceClients,
  updateOutlookFolderMappingSchema,
  type AcquireOutlookGraphAttachmentDto,
  type CancelOutlookFilingRequestDto,
  type CreateOutlookDocumentInsertionDto,
  type CreateOutlookEmailFilingRequestDto,
  type CreateOutlookFolderMappingDto,
  type CreateOutlookSendFileRequestDto,
  type EvaluateOutlookSendPolicyDto,
  type MatterSuggestionDto,
  type MatterSuggestionListDto,
  type MatterSuggestionQueryDto,
  type MatterSuggestionReasonCode,
  type OutlookAddinSessionDto,
  type OutlookAddinSessionExchangeDto,
  type OutlookAddinSessionStatus,
  type OutlookAttachmentRefDto,
  type OutlookAutofileDeniedReasonCode,
  type OutlookAutofileJobDto,
  type OutlookAutofileJobStatus,
  type OutlookDeniedReasonCode,
  type OutlookDocumentInsertionDeniedReasonCode,
  type OutlookDocumentInsertionDto,
  type OutlookDocumentInsertionMode,
  type OutlookDocumentInsertionStatus,
  type OutlookDlpFindingRefDto,
  type OutlookDlpScanFailureCode,
  type OutlookDlpScanReportDto,
  type OutlookDlpScanStatus,
  type OutlookRestrictedDlpFindingType,
  type OutlookFolderMappingApprovalDecision,
  type OutlookFolderMappingApprovalStatus,
  type OutlookFolderMappingDeniedReasonCode,
  type OutlookFolderMappingDto,
  type OutlookFolderMappingMode,
  type OutlookFilingRequestKind,
  type OutlookFilingRequestStatus,
  type OutlookFilingRequestStatusDto,
  type OutlookGraphAttachmentAcquisitionDto,
  type OutlookGraphAttachmentAcquisitionStatus,
  type OutlookIntegrationAdminEvidenceKind,
  type OutlookIntegrationAdminEvidenceStatusDto,
  type OutlookIntegrationAdminFeature,
  type OutlookIntegrationAdminFeatureStatusDto,
  type OutlookIntegrationAdminRing,
  type OutlookIntegrationAdminStatusDto,
  type OutlookItemRefDto,
  type OutlookMailboxBindingStatus,
  type OutlookSendFileRequestStatusDto,
  type OutlookSendPolicyDecision,
  type OutlookSendPolicyDecisionDto,
  type OutlookSendWarningReasonCode,
  type OutlookSourceClient,
  type UpdateOutlookFolderMappingDto,
} from './outlook/outlook-types';
export {
  outlookApprovedGraphScopeRegistry,
  outlookApprovedScopeNames,
  outlookApprovedScopeSetHashSource,
  outlookGraphConsentKinds,
  outlookGraphScopePurposes,
  outlookRejectedGraphScopes,
  type OutlookGraphConsentKind,
  type OutlookGraphScopePurpose,
  type OutlookGraphScopeRegistryEntry,
} from './outlook/outlook-graph-scopes';
export {
  emailMetadataWarningCodes,
  emailParticipantRoles,
  normalizeEmailMetadata,
  type EmailMetadataWarningCode,
  type EmailParticipantRole,
  type NormalizedEmailMetadata,
  type NormalizedEmailParticipant,
} from './email/email-metadata';
export {
  EmlParseError,
  decodeEmlRawContent,
  decodeMimeTextBytes,
  decodeQuotedPrintableBytes,
  decodeRfc2047Words,
  decodeTransferEncodedTextBody,
  extractEmlTextBody,
  parseEmlHeaders,
  parseEmlEnvelope,
  type EmlParseFailureReason,
  type ParsedEmlHeader,
  type ParsedEmlEnvelope,
} from './email/eml-parser';
export {
  canIssueSessionForRole,
  isUserRole,
  userRoles,
  userRoleSchema,
  type UserRole,
} from './permission/roles';
export {
  isRolePermissionAction,
  rolePermissionActions,
  rolePermissionActionSchema,
  type RolePermissionAction,
} from './permission/permission-actions';
export {
  assertCompleteRolePermissionMatrix,
  isRoleAllowedForAction,
  rolePermissionDecision,
  rolePermissionMatrix,
  type RolePermissionDecision,
  type RolePermissionMatrix,
} from './permission/role-permission-matrix';
export {
  allowPermission,
  denyPermission,
  type PermissionDecision,
  type PermissionEffect,
  type PermissionReasonCode,
} from './permission/permission-decision';
export {
  evaluatePermissionCondition,
  permissionAttributeKeys,
  permissionConditionOperators,
  type PermissionAttributeContext,
  type PermissionAttributeKey,
  type PermissionAttributeValue,
  type PermissionConditionEvaluation,
  type PermissionConditionEvaluationOutcome,
  type PermissionConditionOperator,
} from './permission/attribute-policy';
export type {
  DocumentPermissionService,
  PermissionContext,
} from './permission/document-permission.interface';
export { assignUserRoleSchema, type AssignUserRoleDto } from './user/user-role.dto';
export {
  assignAccountLedgerIdSchema,
  type AssignAccountLedgerIdDto,
} from './user/account-ledger.dto';
export type {
  CurrentUserResponseDto,
  LoginCompleteResponseDto,
  LoginMfaRequiredResponseDto,
  LoginRequestDto,
  LoginResponseDto,
  MfaActivateRequestDto,
  MfaEnrollResponseDto,
  MfaVerifyRequestDto,
  PasswordResetAcceptedDto,
  PasswordResetConfirmDto,
  PasswordResetRequestDto,
} from './dto/auth.dto';
export type { TenantSettingsDto } from './dto/tenant-settings.dto';
export {
  uploadDocumentFieldsSchema,
  uploadDocumentTagsSchema,
  type DocumentMetadataSuggestionDto,
  type UploadDocumentFieldsDto,
  type UploadDocumentResponseDto,
} from './dto/document/upload-document.dto';
export {
  quarantinedIntakeResponseSchema,
  type QuarantinedIntakeResponseDto,
} from './dto/document/quarantine-intake.dto';
export {
  documentFolderNameSchema,
  updateDocumentFolderSchema,
  updateDocumentTagsSchema,
  type DocumentFolderDto,
  type DocumentTagListDto,
  type UpdateDocumentFolderDto,
  type UpdateDocumentTagsDto,
} from './dto/document/document-organization.dto';
export {
  createUploadPreflightRequestSchema,
  uploadDuplicateCandidateSchema,
  uploadDuplicateDecisionSchema,
  uploadPreflightPurposeSchema,
  uploadPreflightResponseSchema,
  type CreateUploadPreflightRequestDto,
  type UploadDuplicateCandidateDto,
  type UploadDuplicateDecision,
  type UploadPreflightPurpose,
  type UploadPreflightResponseDto,
} from './dto/document/upload-preflight.dto';
export {
  addDocumentVersionFieldsSchema,
  type AddDocumentVersionFieldsDto,
  type AddDocumentVersionResponseDto,
} from './dto/document/add-version.dto';
export {
  documentVersionStatusSchema,
  documentVersionStatuses,
  listDocumentVersionsQuerySchema,
  type DocumentVersionDto,
  type DocumentVersionListDto,
  type DocumentVersionStatus,
  type ListDocumentVersionsQueryDto,
} from './dto/document/version-list.dto';
export {
  createDocumentComparisonRequestSchema,
  documentComparisonChangeTypeSchema,
  documentComparisonChangeTypes,
  documentComparisonDiffOpSchema,
  documentComparisonDiffOps,
  documentComparisonStatusSchema,
  documentComparisonStatuses,
  type CreateDocumentComparisonRequestDto,
  type DocumentComparisonChangeType,
  type DocumentComparisonClauseChangeDto,
  type DocumentComparisonDiffHunkDto,
  type DocumentComparisonDiffOp,
  type DocumentComparisonDto,
  type DocumentComparisonStatus,
  type DocumentComparisonSummaryDto,
} from './dto/document/document-comparison.dto';
export {
  cancelDocumentEditSessionSchema,
  checkInDocumentEditSessionSchema,
  createDocumentEditSessionSchema,
  assignDocumentSubversionReviewerSchema,
  forceReleaseDocumentEditSessionSchema,
  documentEditClientKindSchema,
  documentEditClientKinds,
  documentEditPackageModeSchema,
  documentEditPackageModes,
  documentEditingFailureReasonSchema,
  documentEditingFailureReasons,
  documentEditSessionStatusSchema,
  documentEditSessionStatuses,
  documentSubversionReviewDecisionSchema,
  documentSubversionReviewDecisions,
  documentSubversionReviewGateStatusSchema,
  documentSubversionReviewGateStatuses,
  documentSubversionStatusSchema,
  documentSubversionStatuses,
  documentSubversionVisibilityScopeSchema,
  documentSubversionVisibilityScopes,
  heartbeatDocumentEditSessionSchema,
  promoteDocumentSubversionSchema,
  saveDocumentSubversionFieldsSchema,
  saveNativeDocumentEditDraftSchema,
  submitDocumentSubversionReviewSchema,
  type CancelDocumentEditSessionDto,
  type CheckInDocumentEditSessionDto,
  type CreateDocumentEditSessionDto,
  type AssignDocumentSubversionReviewerDto,
  type ForceReleaseDocumentEditSessionDto,
  type DocumentEditClientKind,
  type DocumentEditPackageDto,
  type DocumentEditPackageMode,
  type DocumentEditingFailureDto,
  type DocumentEditingFailureReason,
  type DocumentEditSessionDto,
  type DocumentEditSessionStatus,
  type DocumentNativeEditDraftDto,
  type DocumentSubversionDto,
  type DocumentSubversionListDto,
  type DocumentSubversionReviewDecision,
  type DocumentSubversionReviewDto,
  type DocumentSubversionReviewGateDto,
  type DocumentSubversionReviewGateStatus,
  type DocumentSubversionReviewListDto,
  type DocumentSubversionRevisionDto,
  type DocumentSubversionRevisionSummaryDto,
  type DocumentSubversionReviewerListDto,
  type DocumentSubversionReviewerDto,
  type DocumentSubversionStatus,
  type DocumentSubversionVisibilityScope,
  type HeartbeatDocumentEditSessionDto,
  type PromoteDocumentSubversionDto,
  type PromoteDocumentSubversionResponseDto,
  type SaveDocumentSubversionFieldsDto,
  type SaveNativeDocumentEditDraftDto,
  type SubmitDocumentSubversionReviewDto,
} from './dto/document/document-editing.dto';
export {
  updateDocumentMetadataSchema,
  type UpdateDocumentMetadataDto,
} from './dto/document/update-document-metadata.dto';
export {
  previewAccessSessionSchema,
  type PreviewAccessSessionDto,
} from './dto/document/preview-session.dto';
export {
  updateDocumentStatusSchema,
  type UpdateDocumentStatusDto,
} from './dto/document/update-document-status.dto';
export {
  orgDirectoryPurposeSchema,
  orgDirectoryPurposes,
  orgDirectorySubjectFilterSchema,
  orgDirectorySubjectFilters,
  orgDirectorySubjectQuerySchema,
  orgDirectorySubjectTypeSchema,
  orgDirectorySubjectTypes,
  type OrgDirectoryPurpose,
  type OrgDirectorySubjectDto,
  type OrgDirectorySubjectFilter,
  type OrgDirectorySubjectListDto,
  type OrgDirectorySubjectQueryDto,
  type OrgDirectorySubjectType,
} from './dto/org-directory/org-directory.dto';
export {
  documentDownloadReasonCodes,
  documentDownloadReasonCodeSchema,
  documentDownloadReasonQuerySchema,
  type DocumentDownloadReasonCode,
  type DocumentDownloadReasonQueryDto,
} from './dto/document/download-reason.dto';
export { updateLegalHoldSchema, type UpdateLegalHoldDto } from './dto/legal-hold.dto';
export {
  bulkUploadBatchItemStatusSchema,
  bulkUploadBatchItemStatuses,
  bulkUploadBatchStatusSchema,
  bulkUploadBatchStatuses,
  bulkUploadDeadLetterQueueName,
  bulkUploadFileSchema,
  bulkUploadJobItemSchema,
  bulkUploadJobSchema,
  bulkUploadQueueName,
  registerBulkUploadBatchItemSchema,
  registerBulkUploadBatchSchema,
  retryBulkUploadBatchItemSchema,
  type BulkUploadBatchDto,
  type BulkUploadBatchItemDto,
  type BulkUploadBatchItemStatus,
  type BulkUploadBatchStatus,
  type BulkUploadDuplicateItemDto,
  type BulkUploadFailedItemDto,
  type BulkUploadItemResultDto,
  type BulkUploadJobDto,
  type BulkUploadJobItemDto,
  type BulkUploadReportDto,
  type BulkUploadSuccessItemDto,
  type BulkUploadQuarantinedItemDto,
  type RegisterBulkUploadBatchDto,
  type RegisterBulkUploadBatchItemDto,
  type RetryBulkUploadBatchItemDto,
} from './dto/document/bulk-upload.dto';
export {
  auditExportQuerySchema,
  auditQueryActionSchema,
  auditQuerySchema,
  auditResultSchema,
  auditTargetTypeSchema,
  documentAuditQueryEventTypeSchema,
  documentAuditQuerySchema,
  documentTimelineAuditActions,
  matterAuditQuerySchema,
  type AuditEventDto,
  type AuditEventListDto,
  type AuditExportQueryDto,
  type AuditExportResultDto,
  type AuditQueryDto,
  type DocumentAuditEventDto,
  type DocumentAuditEventListDto,
  type DocumentAuditQueryDto,
  type DocumentAuditQueryEventType,
  type DocumentTimelineAuditAction,
  type MatterAuditQueryDto,
} from './dto/audit/audit-query.dto';
export {
  createSavedSearchSchema,
  savedSearchScopeSchema,
  savedSearchScopes,
  searchDocumentTypeFilterSchema,
  searchExtractionStatusSchema,
  searchFiltersSchema,
  searchIsoDateTimeSchema,
  searchLegalHoldSchema,
  searchLegalHoldValues,
  searchOcrConfidenceSchema,
  searchOcrConfidenceValues,
  searchGroupBySchema,
  searchGroupBys,
  searchModeSchema,
  searchModes,
  searchQuerySchema,
  searchPrivacySettingsSchema,
  searchSortSchema,
  searchSorts,
  searchUrlPrivacyModeSchema,
  searchUrlPrivacyModes,
  searchRecordsStatusSchema,
  searchRecordsStatusValues,
  searchTargetSchema,
  searchTargets,
  searchVersionStatusSchema,
  searchVersionStatusValues,
  type CreateSavedSearchDto,
  type SavedSearchDto,
  type SavedSearchListDto,
  type SearchConfidentialityLevel,
  type SearchDateRangeFacetDto,
  type SearchDocumentTypeFilterDto,
  type SearchFacetBucketDto,
  type SearchFacetsDto,
  type SearchFiltersDto,
  type SearchFolderScope,
  type SearchGroupBy,
  type SearchHighlightDto,
  type SearchLegalHold,
  type SearchMode,
  type SearchOcrConfidence,
  type SearchPrivilegeStatus,
  type SearchPrivacySettingsDto,
  type SearchQueryDto,
  type SearchRecordsStatus,
  type SearchResponseDto,
  type SearchResultDto,
  type SearchSort,
  type SearchTarget,
  type SearchUrlPrivacyMode,
  type SearchVersionStatus,
} from './search/search-query.dto';
export {
  searchAdminHealthSchema,
  searchAdminNoResultQuerySchema,
  type SearchAdminHealthDto,
  type SearchAdminNoResultQueryDto,
} from './search/search-admin.dto';
export {
  aiChunkKindSchema,
  aiChunkKinds,
  aiEmbeddingDimension,
  aiEmbeddingDimensions,
  aiEmbeddingModelRouteSchema,
  aiEmbeddingModelRoutes,
  documentChunkProvenanceSchema,
  type AiChunkKind,
  type AiEmbeddingModelRoute,
  type DocumentChunkProvenanceDto,
} from './ai/chunk';
export {
  evidencePackChunkSchema,
  evidencePackGraphFactSchema,
  evidencePackRuleFindingSchema,
  evidencePackSchema,
  evidencePackSourceTypeSchema,
  evidencePackTaskTypeSchema,
  evidencePackTaskTypes,
  evidencePackV2PrepAdapterSchema,
  evidencePackV2PrepSourceRefEntrySchema,
  adaptEvidencePackToPrepSourceRefs,
  type EvidencePackChunkDto,
  type EvidencePackDto,
  type EvidencePackGraphFactDto,
  type EvidencePackRuleFindingDto,
  type EvidencePackTaskType,
  type EvidencePackV2PrepAdapterDto,
  type EvidencePackV2PrepSourceRefEntryDto,
} from './ai/evidence-pack';
export {
  graphConsistencyDriftSchema,
  graphConsistencyResponseSchema,
  graphEdgeTypeSchema,
  graphEdgeTypes,
  graphFactSchema,
  graphFactsQuerySchema,
  graphFactsResponseSchema,
  graphNeighborhoodPathSchema,
  graphNeighborhoodQuerySchema,
  graphNeighborhoodResponseSchema,
  graphNodeCreatedByKindSchema,
  graphNodeCreatedByKindValues,
  graphNodeProvenanceSchema,
  graphNodeProvenanceValues,
  graphNodeRefSchema,
  graphNodeReviewActionSchema,
  graphNodeReviewRequestSchema,
  graphNodeReviewResponseSchema,
  graphNodeReviewStatusSchema,
  graphNodeReviewStatusValues,
  graphNodeTypeSchema,
  graphNodeTypes,
  graphSyncRequestSchema,
  graphSyncResponseSchema,
  type GraphNodeCreatedByKind,
  type GraphConsistencyDriftDto,
  type GraphConsistencyResponseDto,
  type GraphEdgeType,
  type GraphFactDto,
  type GraphFactsQueryDto,
  type GraphFactsResponseDto,
  type GraphNeighborhoodPathDto,
  type GraphNeighborhoodQueryDto,
  type GraphNeighborhoodResponseDto,
  type GraphNodeProvenance,
  type GraphNodeReviewAction,
  type GraphNodeReviewRequestDto,
  type GraphNodeReviewResponseDto,
  type GraphNodeReviewStatus,
  type GraphNodeType,
  type GraphSyncRequestDto,
  type GraphSyncResponseDto,
} from './graph/graph-types';
export {
  contractClassificationSchema,
  clauseBankEntryListResponseSchema,
  clauseBankEntryQuerySchema,
  clauseBankEntrySchema,
  clauseBankEntryStatusSchema,
  clauseBankEntryStatuses,
  clauseSearchRequestSchema,
  clauseSearchResponseSchema,
  clauseSearchResultSchema,
  contractAiReviewFindingListResponseSchema,
  contractAiReviewFindingQuerySchema,
  contractAiReviewFindingSchema,
  contractAiReviewStatusSchema,
  contractAiReviewStatuses,
  contractAiReviewTaskSchema,
  contractAiReviewTasks,
  contractClauseKindSchema,
  contractClauseKinds,
  contractClauseBankItemSchema,
  contractClauseBankQuerySchema,
  contractClauseBankResponseSchema,
  contractProcessRequestSchema,
  contractProcessResponseSchema,
  contractRuleFindingSchema,
  contractRuleFindingsQuerySchema,
  contractRuleFindingsResponseSchema,
  contractRuleFindingStatusSchema,
  contractTypeSchema,
  contractTypes,
  counterpartyPatternSchema,
  counterpartyPatternsQuerySchema,
  counterpartyPatternsResponseSchema,
  createClauseBankEntryRequestSchema,
  createNegotiationPositionRequestSchema,
  createPlaybookRuleRequestSchema,
  negotiationClauseKindSchema,
  negotiationClauseKinds,
  negotiationIssueListResponseSchema,
  negotiationIssueQuerySchema,
  negotiationIssueSchema,
  negotiationIssueStatusSchema,
  negotiationIssueStatuses,
  negotiationPositionListResponseSchema,
  negotiationPositionQuerySchema,
  negotiationPositionSchema,
  playbookRuleResponseSchema,
  playbookRuleSeveritySchema,
  playbookRuleTypeSchema,
  playbookRuleTypes,
  redlineChangeTypeSchema,
  redlineChangeTypes,
  updateClauseBankEntryRequestSchema,
  updateNegotiationIssueStatusRequestSchema,
  updateNegotiationPositionRequestSchema,
  wordClauseInsertionRequestSchema,
  wordClauseInsertionResponseSchema,
  type ClauseBankEntryDto,
  type ClauseBankEntryListResponseDto,
  type ClauseBankEntryQueryDto,
  type ClauseBankEntryStatus,
  type ClauseSearchRequestDto,
  type ClauseSearchResponseDto,
  type ClauseSearchResultDto,
  type ContractAiReviewFindingDto,
  type ContractAiReviewFindingListResponseDto,
  type ContractAiReviewFindingQueryDto,
  type ContractAiReviewStatus,
  type ContractAiReviewTask,
  type ContractClauseBankItemDto,
  type ContractClauseBankQueryDto,
  type ContractClauseBankResponseDto,
  type ContractClassificationDto,
  type ContractClauseKind,
  type ContractProcessRequestDto,
  type ContractProcessResponseDto,
  type ContractRuleFindingDto,
  type ContractRuleFindingStatus,
  type ContractRuleFindingsQueryDto,
  type ContractRuleFindingsResponseDto,
  type ContractType,
  type CounterpartyPatternDto,
  type CounterpartyPatternsQueryDto,
  type CounterpartyPatternsResponseDto,
  type CreateClauseBankEntryRequestDto,
  type CreateNegotiationPositionRequestDto,
  type CreatePlaybookRuleRequestDto,
  type NegotiationClauseKind,
  type NegotiationIssueDto,
  type NegotiationIssueListResponseDto,
  type NegotiationIssueQueryDto,
  type NegotiationIssueStatus,
  type NegotiationPositionDto,
  type NegotiationPositionListResponseDto,
  type NegotiationPositionQueryDto,
  type PlaybookRuleResponseDto,
  type PlaybookRuleSeverity,
  type PlaybookRuleType,
  type RedlineChangeType,
  type UpdateClauseBankEntryRequestDto,
  type UpdateNegotiationIssueStatusRequestDto,
  type UpdateNegotiationPositionRequestDto,
  type WordClauseInsertionRequestDto,
  type WordClauseInsertionResponseDto,
} from './contract/contract-types';
export {
  aiModelRouteSchema,
  aiModelTierSchema,
  aiRoutingDecisionSchema,
  aiRoutingEffectSchema,
  aiTaskKindSchema,
  aiTaskRiskSchema,
  type AiModelRoute,
  type AiRoutingDecisionDto,
  type AiRoutingEffect,
  type AiTaskKind,
  type AiTaskRisk,
} from './ai/model-routing';
export {
  aiCitationClaimSchema,
  aiCitationSchema,
  aiCitationSourceRequestSchema,
  aiCitationSourceResponseSchema,
  aiCitationSourceSchema,
  aiCitationVerificationRequestSchema,
  aiCitationVerificationResponseSchema,
  aiCitationVerificationWarningSchema,
  aiCitationWarningCodeSchema,
  type AiCitationClaimDto,
  type AiCitationDto,
  type AiCitationSourceDto,
  type AiCitationSourceRequestDto,
  type AiCitationSourceResponseDto,
  type AiCitationVerificationRequestDto,
  type AiCitationVerificationResponseDto,
  type AiCitationVerificationWarningDto,
  type AiCitationWarningCode,
} from './ai/citation';
export {
  aiClaimCitationLedgerSchema,
  aiClaimLedgerSchema,
  aiClaimVerificationStatusSchema,
  aiSessionClaimsResponseSchema,
  type AiClaimCitationLedgerDto,
  type AiClaimLedgerDto,
  type AiClaimVerificationStatus,
  type AiSessionClaimsResponseDto,
} from './ai/claims-ledger';
export {
  aiGroundedClaimKindSchema,
  aiGroundedClaimSchema,
  aiGroundedGenerationOutputSchema,
  aiGroundedSectionSchema,
  aiGroundedSourceRefSchema,
  type AiGroundedClaimDto,
  type AiGroundedClaimKind,
  type AiGroundedGenerationOutputDto,
  type AiGroundedSectionDto,
} from './ai/generation';
export {
  aiPrepArtifactKinds,
  aiPrepArtifactAllowedClaimKinds,
  aiPrepArtifactClaimKindAllowlist,
  aiPrepArtifactKindSchema,
  aiPrepArtifactPayloadForKindSchema,
  aiPrepArtifactPayloadSchema,
  aiPrepArtifactSummarySchema,
  aiPrepClaimKinds,
  aiPrepClaimKindSchema,
  aiPrepDocumentReadinessStatuses,
  aiPrepDocumentReadinessStatusSchema,
  aiPrepDocumentStatusSchema,
  aiPrepFeedbackKinds,
  aiPrepFeedbackKindSchema,
  aiPrepFeedbackReasonCodes,
  aiPrepFeedbackReasonCodeSchema,
  aiPrepFeedbackRequestSchema,
  aiPrepFeedbackResponseSchema,
  aiPrepMatterDocumentReadinessSchema,
  aiPrepMatterReadinessSchema,
  aiPrepMatterRetryResponseSchema,
  aiPrepMatterTimelineItemSchema,
  aiPrepPayloadBannedTopLevelKeys,
  aiPrepGroundedGenerationOutputSchema,
  parseAiPrepArtifactPayload,
  aiPrepStaleReasons,
  aiPrepStaleReasonSchema,
  aiPrepStatuses,
  aiPrepStatusSchema,
  type AiPrepArtifactKind,
  type AiPrepArtifactPayloadDto,
  type AiPrepArtifactSummaryDto,
  type AiPrepClaimKind,
  type AiPrepDocumentReadinessStatus,
  type AiPrepDocumentStatusDto,
  type AiPrepFeedbackKind,
  type AiPrepFeedbackReasonCode,
  type AiPrepFeedbackRequestDto,
  type AiPrepFeedbackResponseDto,
  type AiPrepMatterDocumentReadinessDto,
  type AiPrepMatterReadinessDto,
  type AiPrepMatterRetryResponseDto,
  type AiPrepMatterTimelineItemDto,
  type AiPrepStaleReason,
  type AiPrepStatus,
} from './ai/prep';
export {
  localAiEndpointClasses,
  localAiEndpointClassSchema,
  localAiEvalReportSchema,
  localAiOpsHealthSchema,
  localAiOpsMetricsSchema,
  localAiRuntimeStatuses,
  localAiRuntimeStatusSchema,
  type LocalAiEndpointClass,
  type LocalAiEvalReportDto,
  type LocalAiOpsHealthDto,
  type LocalAiOpsMetricsDto,
  type LocalAiRuntimeStatus,
} from './ai/ops';
export {
  aiSummaryRequestSchema,
  aiSummaryExcludedSourcesNoticeSchema,
  aiSummaryOpenQuestionSchema,
  aiSummaryRecommendedActionSchema,
  aiSummaryResponseSchema,
  aiSummarySectionSchema,
  aiSummaryStatusSchema,
  aiSummaryTaskSchema,
  aiSummaryWarningCodeSchema,
  type AiSummaryExcludedSourcesNoticeDto,
  type AiSummaryOpenQuestionDto,
  type AiSummaryRecommendedActionDto,
  type AiSummaryRequestDto,
  type AiSummaryResponseDto,
  type AiSummarySectionDto,
  type AiSummaryStatus,
  type AiSummaryTask,
  type AiSummaryWarningCode,
} from './ai/summary';
export {
  aiFeedbackCorrectionTypes,
  aiFeedbackErrorTypes,
  aiFeedbackMetricsSchema,
  aiFeedbackRequestSchema,
  aiFeedbackResponseSchema,
  type AiFeedbackCorrectionType,
  type AiFeedbackErrorType,
  type AiFeedbackMetricsDto,
  type AiFeedbackRequestDto,
  type AiFeedbackResponseDto,
} from './ai/feedback';
export {
  aiSessionChunkDetailSchema,
  aiSessionChunkLogSchema,
  aiSessionChunkReasonCodeSchema,
  aiSessionCreateSchema,
  aiSessionDetailSchema,
  aiSessionListItemSchema,
  aiSessionListSchema,
  aiSessionModelRouteSchema,
  aiSessionPayloadSchema,
  aiSessionResponseLogSchema,
  aiSessionStatusSchema,
  listAiSessionsQuerySchema,
  type AiSessionChunkDetailDto,
  type AiSessionChunkLogDto,
  type AiSessionChunkReasonCode,
  type AiSessionCreateDto,
  type AiSessionDetailDto,
  type AiSessionListDto,
  type AiSessionListItemDto,
  type AiSessionModelRoute,
  type AiSessionPayloadDto,
  type AiSessionResponseLogDto,
  type AiSessionStatus,
  type ListAiSessionsQueryDto,
} from './ai/session';

export {
  clientConfidentialityLevels,
  clientConfidentialityLevelSchema,
  clientStatuses,
  clientStatusSchema,
  clientTypes,
  clientTypeSchema,
  type ClientConfidentialityLevel,
  type ClientStatus,
  type ClientType,
} from './client/client-enums';
export {
  createClientSchema,
  listClientsQuerySchema,
  updateClientSchema,
  type ClientDto,
  type ClientListDto,
  type CreateClientDto,
  type ListClientsQueryDto,
  type UpdateClientDto,
} from './client/client.dto';
export {
  matterAppLookupQuerySchema,
  matterAppLookupResponseSchema,
  matterAppMatterOptionSchema,
  matterAppSourceModeSchema,
  matterAppSourceModes,
  matterAppSourceStatusSchema,
  matterAppUnavailableReasonSchema,
  matterAppUnavailableReasons,
  type MatterAppLookupQueryDto,
  type MatterAppLookupResponseDto,
  type MatterAppMatterOptionDto,
  type MatterAppSourceMode,
  type MatterAppSourceStatusDto,
  type MatterAppUnavailableReason,
} from './dto/matter-app/matter-app.dto';
export { matterTypes, matterTypeSchema, type MatterType } from './matter/matter-type';
export {
  containsSensitiveMatterMetadataKey,
  isMatterDateRangeValid,
  matterMetadataSchema,
  matterOptionalDateSchema,
} from './matter/matter-validation';
export {
  conflictCandidateSourceTypeSchema,
  conflictCandidateSourceTypes,
  conflictCheckStatusSchema,
  conflictCheckStatuses,
  resolveConflictCheckSchema,
  type ConflictCheckCandidateDto,
  type ConflictCheckDto,
  type ConflictCheckListDto,
  type ConflictCheckStatus,
  type ResolveConflictCheckDto,
} from './matter/conflict-check.dto';
export {
  createMatterSchema,
  listMattersQuerySchema,
  matterAccessScopes,
  matterAccessScopeSchema,
  matterConflictStatuses,
  matterConflictStatusSchema,
  matterIntakeTemplateAccessScopes,
  matterIntakeTemplateCodeSchema,
  matterIntakeTemplateCodes,
  matterIssueRiskLevelSchema,
  matterIssueRiskLevels,
  matterIssueStatusSchema,
  matterIssueStatuses,
  matterClosingChecklistItemCodeSchema,
  matterClosingChecklistItemCodes,
  matterClosingChecklistStatusSchema,
  matterClosingChecklistStatuses,
  matterClosingBinderItemTypeSchema,
  matterClosingBinderItemTypes,
  matterClosingBinderStatusSchema,
  matterClosingBinderStatuses,
  matterWikiPageKindSchema,
  matterWikiPageKinds,
  matterWikiPageProvenanceSchema,
  matterWikiPageProvenances,
  matterWikiReviewActionSchema,
  matterWikiReviewActions,
  matterWikiReviewStatusSchema,
  matterWikiReviewStatuses,
  knowledgeCandidateReviewActionSchema,
  knowledgeCandidateReviewActions,
  knowledgeCandidateStatusSchema,
  knowledgeCandidateStatuses,
  knowledgeCandidateTypeSchema,
  knowledgeCandidateTypes,
  matterKeyDateSourceTypeSchema,
  matterKeyDateSourceTypes,
  matterKeyDateStatusSchema,
  matterKeyDateStatuses,
  matterKeyDateTypeSchema,
  matterKeyDateTypes,
  matterConfidentialityLevelSchema,
  matterConfidentialityLevels,
  matterRelationTypeSchema,
  matterRelationTypes,
  createMatterIssueSchema,
  createMatterKeyDateSchema,
  createMatterRelatedMatterSchema,
  deleteMatterRelatedMatterQuerySchema,
  matterStatuses,
  matterStatusSchema,
  updateMatterIssueSchema,
  updateMatterKeyDateSchema,
  waiveMatterClosingChecklistItemSchema,
  reviewMatterWikiPageSchema,
  reviewKnowledgeCandidateSchema,
  updateMatterSchema,
  updateMatterStatusSchema,
  type MatterClosingChecklistDto,
  type MatterClosingChecklistItemCode,
  type MatterClosingChecklistItemDto,
  type MatterClosingChecklistStatus,
  type MatterClosingBinderDto,
  type MatterClosingBinderItemType,
  type MatterClosingBinderManifestDownloadDto,
  type MatterClosingBinderManifestDto,
  type MatterClosingBinderManifestItemDto,
  type MatterClosingBinderResponseDto,
  type MatterClosingBinderStatus,
  type KnowledgeCandidateDto,
  type KnowledgeCandidateReviewAction,
  type KnowledgeCandidateStatus,
  type KnowledgeCandidateType,
  type MatterWikiExportDto,
  type MatterWikiListDto,
  type MatterWikiPageDto,
  type MatterWikiPageKind,
  type MatterWikiPageProvenance,
  type MatterWikiRegenerateResponseDto,
  type MatterWikiReviewAction,
  type MatterWikiReviewStatus,
  type MatterWikiSourceRefDto,
  type CreateMatterIssueDto,
  type CreateMatterKeyDateDto,
  type CreateMatterDto,
  type CreateMatterRelatedMatterDto,
  type DeleteMatterRelatedMatterQueryDto,
  type ListMattersQueryDto,
  type MatterAccessScope,
  type MatterConfidentialityLevel,
  type MatterConflictStatus,
  type MatterDashboardAiSessionDto,
  type MatterDashboardDto,
  type MatterDashboardExternalActivityDto,
  type MatterDashboardIssueSummaryDto,
  type MatterDashboardKeyDateDto,
  type MatterDashboardKeyDocumentDto,
  type MatterDashboardMatterSummaryDto,
  type MatterDashboardRecentActivityDto,
  type MatterDto,
  type MatterIntakeTemplateCode,
  type MatterIssueDto,
  type MatterIssueListDto,
  type MatterIssueRiskLevel,
  type MatterIssueStatus,
  type MatterKeyDateDto,
  type MatterKeyDateListDto,
  type MatterKeyDateSourceType,
  type MatterKeyDateStatus,
  type MatterKeyDateType,
  type MatterListDto,
  type MatterRelatedMatterDto,
  type MatterRelatedMatterListDto,
  type MatterRelationType,
  type MatterStatus,
  type UpdateMatterIssueDto,
  type UpdateMatterKeyDateDto,
  type UpdateMatterDto,
  type UpdateMatterStatusDto,
  type WaiveMatterClosingChecklistItemDto,
  type ReviewKnowledgeCandidateDto,
  type ReviewMatterWikiPageDto,
} from './matter/matter.dto';
export {
  addMatterMemberSchema,
  matterMemberAccessLevelSchema,
  matterMemberAccessLevels,
  matterMemberRoleSchema,
  matterMemberRoles,
  matterLeadRoles,
  updateMatterMemberSchema,
  type AddMatterMemberDto,
  type MatterLeadRole,
  type MatterMemberAccessLevel,
  type MatterMemberDto,
  type MatterMemberListDto,
  type MatterMemberRole,
  type UpdateMatterMemberDto,
} from './matter/matter-member.dto';
export {
  ethicalWallMembershipInputSchema,
  createEthicalWallSchema,
  ethicalWallStatuses,
  listEthicalWallsQuerySchema,
  wallMembershipTypes,
  wallSubjectTypes,
  type AddEthicalWallMembershipDto,
  type CreateEthicalWallDto,
  type CreateEthicalWallMemberDto,
  type EthicalWallDetailDto,
  type EthicalWallDto,
  type EthicalWallListDto,
  type EthicalWallMembershipDto,
  type EthicalWallStatus,
  type ListEthicalWallsQueryDto,
  type WallMembershipType,
  type WallSubjectType,
} from './ethical-wall/ethical-wall.dto';
export {
  partyRoleSchema,
  partyRoles,
  partyTypeSchema,
  partyTypes,
  type PartyRole,
  type PartyType,
} from './party/party-enums';
export {
  createPartySchema,
  listPartiesQuerySchema,
  updatePartySchema,
  type CreatePartyDto,
  type ListPartiesQueryDto,
  type PartyDto,
  type PartyListDto,
  type UpdatePartyDto,
} from './party/party.dto';
