import { z } from 'zod';

export const ERROR_CODES = [
  'AUTH_REQUIRED',
  'PERMISSION_DENIED',
  'ETHICAL_WALL_BLOCKED',
  'AI_POLICY_BLOCKED',
  'DOCUMENT_LOCKED',
  'VALIDATION_FAILED',
  'UNSUPPORTED_FILE_TYPE',
  'EXTERNAL_LINK_EXPIRED',
  'TENANT_ISOLATION_VIOLATION',
] as const;

export type ErrorCode = (typeof ERROR_CODES)[number];

export const errorCodeSchema = z.enum(ERROR_CODES);

export interface ApiErrorResponse {
  code: ErrorCode;
  message?: string;
  requestId?: string;
}

export {
  auditActions,
  auditMetadataKeys,
  isAuditAction,
  isAuditMetadataKey,
  r1AuditActions,
  r2DocumentAuditActions,
  r3SearchAuditActions,
  r4DlpAuditActions,
  r4EmailAuditActions,
  r5AuditConsoleActions,
  r5BreakGlassAuditActions,
  r6AiAuditActions,
  r6AiPrepAuditActions,
  r6AiFeedbackAuditActions,
  r6AiPolicyAuditActions,
  r7GraphAuditActions,
  r8ContractAuditActions,
  r9DdAuditActions,
  r10LitigationAuditActions,
  r11ExternalAuditActions,
  r12RecordsAuditActions,
  r13EnterpriseAuditActions,
  r14ScaleLearningAuditActions,
  outlookAuditActions,
  type AuditAction,
  type AuditMetadata,
  type AuditMetadataKey,
  type AuditMetadataValue,
  type R1AuditAction,
  type R2DocumentAuditAction,
  type R3SearchAuditAction,
  type R4DlpAuditAction,
  type R4EmailAuditAction,
  type R5AuditConsoleAction,
  type R5BreakGlassAuditAction,
  type R6AiAuditAction,
  type R6AiPrepAuditAction,
  type R6AiFeedbackAuditAction,
  type R6AiPolicyAuditAction,
  type R7GraphAuditAction,
  type R8ContractAuditAction,
  type R9DdAuditAction,
  type R10LitigationAuditAction,
  type R11ExternalAuditAction,
  type R12RecordsAuditAction,
  type R13EnterpriseAuditAction,
  type R14ScaleLearningAuditAction,
  type OutlookAuditAction,
} from './types/audit';

export {
  createScaleAiGateReviewRequestSchema,
  createScaleCostSnapshotRequestSchema,
  createScaleEvalRunRequestSchema,
  createScaleLearningEventRequestSchema,
  createScaleMigrationDrillRequestSchema,
  createScalePerformanceRunRequestSchema,
  scaleAiGateDecisionSchema,
  scaleAiGateDecisions,
  scaleAiGateReviewListResponseSchema,
  scaleAiGateReviewSchema,
  scaleCostScopeSchema,
  scaleCostScopes,
  scaleCostSnapshotListResponseSchema,
  scaleCostSnapshotSchema,
  scaleEvalRunListResponseSchema,
  scaleEvalRunSchema,
  scaleEvalSuiteSchema,
  scaleEvalSuites,
  scaleLearningCategorySchema,
  scaleLearningCategories,
  scaleLearningEventListResponseSchema,
  scaleLearningEventSchema,
  scaleMigrationDrillListResponseSchema,
  scaleMigrationDrillSchema,
  scaleMigrationScopeSchema,
  scaleMigrationScopes,
  scalePerformanceRunListResponseSchema,
  scalePerformanceRunSchema,
  scaleReadinessSummarySchema,
  scaleRunStatusSchema,
  scaleRunStatuses,
  scaleScenarioSchema,
  scaleScenarios,
  type CreateScaleAiGateReviewRequestDto,
  type CreateScaleCostSnapshotRequestDto,
  type CreateScaleEvalRunRequestDto,
  type CreateScaleLearningEventRequestDto,
  type CreateScaleMigrationDrillRequestDto,
  type CreateScalePerformanceRunRequestDto,
  type ScaleAiGateReviewDto,
  type ScaleAiGateReviewListResponseDto,
  type ScaleCostSnapshotDto,
  type ScaleCostSnapshotListResponseDto,
  type ScaleEvalRunDto,
  type ScaleEvalRunListResponseDto,
  type ScaleLearningEventDto,
  type ScaleLearningEventListResponseDto,
  type ScaleMigrationDrillDto,
  type ScaleMigrationDrillListResponseDto,
  type ScalePerformanceRunDto,
  type ScalePerformanceRunListResponseDto,
  type ScaleReadinessSummaryDto,
} from './scale/scale-types';

export {
  createEnterpriseBackupSnapshotRequestSchema,
  createEnterpriseComplianceEvidenceRequestSchema,
  createEnterpriseKeyReferenceRequestSchema,
  createEnterpriseSiemExportRequestSchema,
  createEnterpriseSsoProviderRequestSchema,
  enterpriseBackupScopeSchema,
  enterpriseBackupScopes,
  enterpriseBackupSnapshotListResponseSchema,
  enterpriseBackupSnapshotSchema,
  enterpriseBackupStatusSchema,
  enterpriseBackupStatuses,
  enterpriseComplianceEvidenceListResponseSchema,
  enterpriseComplianceEvidenceSchema,
  enterpriseComplianceFrameworkSchema,
  enterpriseComplianceFrameworks,
  enterpriseComplianceStatusSchema,
  enterpriseComplianceStatuses,
  enterpriseKeyProviderSchema,
  enterpriseKeyProviders,
  enterpriseKeyReferenceListResponseSchema,
  enterpriseKeyReferenceSchema,
  enterpriseKeyStatusSchema,
  enterpriseKeyStatuses,
  enterpriseReadinessSummarySchema,
  enterpriseSiemExportListResponseSchema,
  enterpriseSiemExportSchema,
  enterpriseSiemSinkTypeSchema,
  enterpriseSiemSinkTypes,
  enterpriseSsoEnforcementModeSchema,
  enterpriseSsoEnforcementModes,
  enterpriseSsoProviderListResponseSchema,
  enterpriseSsoProviderSchema,
  enterpriseSsoProviderStatusSchema,
  enterpriseSsoProviderStatuses,
  enterpriseSsoSpMetadataSchema,
  type CreateEnterpriseBackupSnapshotRequestDto,
  type CreateEnterpriseComplianceEvidenceRequestDto,
  type CreateEnterpriseKeyReferenceRequestDto,
  type CreateEnterpriseSiemExportRequestDto,
  type CreateEnterpriseSsoProviderRequestDto,
  type EnterpriseBackupSnapshotDto,
  type EnterpriseBackupSnapshotListResponseDto,
  type EnterpriseComplianceEvidenceDto,
  type EnterpriseComplianceEvidenceListResponseDto,
  type EnterpriseKeyReferenceDto,
  type EnterpriseKeyReferenceListResponseDto,
  type EnterpriseReadinessSummaryDto,
  type EnterpriseSiemExportDto,
  type EnterpriseSiemExportListResponseDto,
  type EnterpriseSsoProviderDto,
  type EnterpriseSsoProviderListResponseDto,
  type EnterpriseSsoSpMetadataDto,
} from './enterprise/enterprise-types';

export {
  createArchiveRequestSchema,
  createDisposalRequestSchema,
  createLegalHoldRequestSchema,
  createRetentionPolicyRequestSchema,
  disposalCertificateSchema,
  disposalRequestSchema,
  disposalRequestStatusSchema,
  disposalRequestStatuses,
  legalHoldListResponseSchema,
  legalHoldSchema,
  legalHoldScopeSchema,
  legalHoldScopes,
  legalHoldStatusSchema,
  legalHoldStatuses,
  recordsArchiveSchema,
  retentionPolicyListResponseSchema,
  retentionPolicySchema,
  retentionPolicyStatusSchema,
  retentionPolicyStatuses,
  type CreateArchiveRequestDto,
  type CreateDisposalRequestDto,
  type CreateLegalHoldRequestDto,
  type CreateRetentionPolicyRequestDto,
  type DisposalCertificateDto,
  type DisposalRequestDto,
  type DisposalRequestStatus,
  type LegalHoldDto,
  type LegalHoldListResponseDto,
  type LegalHoldScope,
  type LegalHoldStatus,
  type RecordsArchiveDto,
  type RetentionPolicyDto,
  type RetentionPolicyListResponseDto,
} from './records/records-types';
export {
  dashboardAiPrepStatusSchema,
  dashboardIntegrationStatusSchema,
  dashboardOverviewSchema,
  dashboardPolicyAlertSchema,
  dashboardRecentActivitySchema,
  dashboardRecentFileSchema,
  dashboardSectionIds,
  type DashboardAiPrepStatusDto,
  type DashboardIntegrationStatusDto,
  type DashboardOverviewDto,
  type DashboardPolicyAlertDto,
  type DashboardRecentActivityDto,
  type DashboardRecentFileDto,
  type DashboardSectionId,
} from './dashboard/dashboard-types';
export {
  createDdDataRoomMappingRequestSchema,
  createDdIssueRequestSchema,
  createDdRfiRequestSchema,
  createDdRiskRequestSchema,
  ddDataRoomMappingListResponseSchema,
  ddDataRoomMappingQuerySchema,
  ddDataRoomMappingSchema,
  ddIssueListResponseSchema,
  ddIssueQuerySchema,
  ddIssueSchema,
  ddIssueSeveritySchema,
  ddIssueStatusSchema,
  ddIssueSeverities,
  ddIssueStatuses,
  ddMappingStatusSchema,
  ddMappingStatuses,
  ddPriorities,
  ddPrioritySchema,
  ddRfiCategories,
  ddRfiCategorySchema,
  ddRfiListResponseSchema,
  ddRfiQuerySchema,
  ddRfiSchema,
  ddRfiStatusSchema,
  ddRfiStatuses,
  ddRiskCategories,
  ddRiskCategorySchema,
  ddRiskLikelihoodSchema,
  ddRiskLikelihoods,
  ddRiskListResponseSchema,
  ddRiskQuerySchema,
  ddRiskSchema,
  ddRiskStatusSchema,
  ddRiskStatuses,
  ddTraceabilityQuerySchema,
  ddTraceabilityResponseSchema,
  ddTraceabilityItemSchema,
  updateDdRfiRequestSchema,
  type CreateDdDataRoomMappingRequestDto,
  type CreateDdIssueRequestDto,
  type CreateDdRfiRequestDto,
  type CreateDdRiskRequestDto,
  type DdDataRoomMappingDto,
  type DdDataRoomMappingListResponseDto,
  type DdDataRoomMappingQueryDto,
  type DdIssueDto,
  type DdIssueListResponseDto,
  type DdIssueQueryDto,
  type DdIssueSeverity,
  type DdIssueStatus,
  type DdMappingStatus,
  type DdPriority,
  type DdRfiCategory,
  type DdRfiDto,
  type DdRfiListResponseDto,
  type DdRfiQueryDto,
  type DdRfiStatus,
  type DdRiskCategory,
  type DdRiskDto,
  type DdRiskLikelihood,
  type DdRiskListResponseDto,
  type DdRiskQueryDto,
  type DdRiskStatus,
  type DdTraceabilityItemDto,
  type DdTraceabilityQueryDto,
  type DdTraceabilityResponseDto,
  type UpdateDdRfiRequestDto,
} from './dd/dd-types';

export {
  createLitigationEvidenceRequestSchema,
  createLitigationFactRequestSchema,
  createLitigationIssueRequestSchema,
  createLitigationPleadingRequestSchema,
  litigationAdmittedStatusSchema,
  litigationAdmittedStatuses,
  litigationCaseMapItemSchema,
  litigationCaseMapQuerySchema,
  litigationCaseMapResponseSchema,
  litigationCustodyStatusSchema,
  litigationCustodyStatuses,
  litigationEvidenceListResponseSchema,
  litigationEvidenceQuerySchema,
  litigationEvidenceSchema,
  litigationEvidenceTypeSchema,
  litigationEvidenceTypes,
  litigationFactListResponseSchema,
  litigationFactQuerySchema,
  litigationFactSchema,
  litigationFactStatusSchema,
  litigationFactStatuses,
  litigationIssueListResponseSchema,
  litigationIssueQuerySchema,
  litigationIssueSchema,
  litigationIssueStatusSchema,
  litigationIssueStatuses,
  litigationIssueTypeSchema,
  litigationIssueTypes,
  litigationMaterialities,
  litigationMaterialitySchema,
  litigationPleadingListResponseSchema,
  litigationPleadingQuerySchema,
  litigationPleadingSchema,
  litigationPleadingStatusSchema,
  litigationPleadingStatuses,
  litigationPleadingTypeSchema,
  litigationPleadingTypes,
  type CreateLitigationEvidenceRequestDto,
  type CreateLitigationFactRequestDto,
  type CreateLitigationIssueRequestDto,
  type CreateLitigationPleadingRequestDto,
  type LitigationAdmittedStatus,
  type LitigationCaseMapItemDto,
  type LitigationCaseMapQueryDto,
  type LitigationCaseMapResponseDto,
  type LitigationCustodyStatus,
  type LitigationEvidenceDto,
  type LitigationEvidenceListResponseDto,
  type LitigationEvidenceQueryDto,
  type LitigationEvidenceType,
  type LitigationFactDto,
  type LitigationFactListResponseDto,
  type LitigationFactQueryDto,
  type LitigationFactStatus,
  type LitigationIssueDto,
  type LitigationIssueListResponseDto,
  type LitigationIssueQueryDto,
  type LitigationIssueStatus,
  type LitigationIssueType,
  type LitigationMateriality,
  type LitigationPleadingDto,
  type LitigationPleadingListResponseDto,
  type LitigationPleadingQueryDto,
  type LitigationPleadingStatus,
  type LitigationPleadingType,
} from './litigation/litigation-types';

export {
  acceptExternalNdaRequestSchema,
  createExternalAnswerRequestSchema,
  createExternalLinkRequestSchema,
  createExternalQuestionRequestSchema,
  createExternalUserRequestSchema,
  createExternalWorkspaceRequestSchema,
  externalAccessManifestSchema,
  externalAccessStatusResponseSchema,
  externalAccessStatusSchema,
  externalAccessStatuses,
  externalDlpWarningStatusSchema,
  externalDlpWarningStatuses,
  externalDownloadTicketSchema,
  externalLinkCreatedResponseSchema,
  externalLinkSchema,
  externalLinkStatusSchema,
  externalLinkStatuses,
  externalNdaAcceptanceSchema,
  externalQaDirectionSchema,
  externalQaDirections,
  externalQaListResponseSchema,
  externalQaMessageSchema,
  externalUserSchema,
  externalUserStatusSchema,
  externalUserStatuses,
  externalWorkspaceSchema,
  externalWorkspaceStatusSchema,
  externalWorkspaceStatuses,
  type AcceptExternalNdaRequestDto,
  type CreateExternalAnswerRequestDto,
  type CreateExternalLinkRequestDto,
  type CreateExternalQuestionRequestDto,
  type CreateExternalUserRequestDto,
  type CreateExternalWorkspaceRequestDto,
  type ExternalAccessManifestDto,
  type ExternalAccessStatus,
  type ExternalAccessStatusResponseDto,
  type ExternalDlpWarningStatus,
  type ExternalDownloadTicketDto,
  type ExternalLinkCreatedResponseDto,
  type ExternalLinkDto,
  type ExternalLinkStatus,
  type ExternalNdaAcceptanceDto,
  type ExternalQaDirection,
  type ExternalQaListResponseDto,
  type ExternalQaMessageDto,
  type ExternalUserDto,
  type ExternalUserStatus,
  type ExternalWorkspaceDto,
  type ExternalWorkspaceStatus,
} from './external/external-types';

export {
  aiModelRouteKeys,
  aiModelTiers,
  aiPolicyBlockReasonCodes,
  aiPolicyBlockedResponse,
  aiPolicyPurposes,
  type AiDocumentPolicyDecision,
  type AiModelRouteKey,
  type AiModelTier,
  type AiPolicyAuditResult,
  type AiPolicyBlockReasonCode,
  type AiPolicyBlockedResponse,
  type AiPolicyDecisionEffect,
  type AiPolicyDefaultEffect,
  type AiPolicyEvaluationRequest,
  type AiPolicyEvaluationResult,
  type AiPolicyPurpose,
  type AiPolicySchema,
} from './types/ai-policy';
export {
  breakGlassReasonCodes,
  breakGlassRequestStatuses,
  createBreakGlassRequestSchema,
  revokeBreakGlassRequestSchema,
  type BreakGlassReasonCode,
  type BreakGlassRequestDto,
  type BreakGlassRequestStatus,
  type CreateBreakGlassRequestDto,
  type RevokeBreakGlassRequestDto,
} from './break-glass/break-glass.dto';

export {
  tenantStatuses,
  workspaceStatuses,
  type TenantId,
  type TenantStatus,
  type TenantSummary,
  type WorkspaceStatus,
} from './types/tenant';
export { userStatuses, type UserStatus, type UserSummary } from './types/user';
export type { FileObjectDto } from './types/file-object';
export { buildSafeLabel, type DisplayFieldsDto } from './display/display-fields.dto';
export {
  documentConfidentialityLevelSchema,
  documentConfidentialityLevels,
  documentPrivilegeStatusSchema,
  documentPrivilegeStatuses,
  documentExtractionMethods,
  documentExtractionStatuses,
  documentStatusSchema,
  documentStatuses,
  documentTypeSchema,
  documentTypes,
  listDocumentSortSchema,
  listDocumentSortValues,
  listDocumentsQuerySchema,
  type DocumentConfidentialityLevel,
  type DocumentDto,
  type DocumentExtractionMethod,
  type DocumentExtractionStatus,
  type DocumentListDto,
  type DocumentPrivilegeStatus,
  type DocumentStatus,
  type DocumentType,
  type ListDocumentSort,
  type ListDocumentsQueryDto,
} from './types/document';
export {
  dlpFindingTypes,
  dlpRuleIds,
  type DlpDetection,
  type DlpFindingType,
  type DlpRuleId,
  type DlpScanOptions,
} from './dlp/dlp-types';
export {
  emailFailureReasonCodes,
  emailMatterWarningCodes,
  emailMatterSuggestionQuerySchema,
  emailPrivilegeSuggestionReasonCodes,
  emailPrivilegeTagSuggestions,
  emailParserKinds,
  emailParseStatuses,
  fileEmailToMatterSchema,
  uploadEmailToMatterFieldsSchema,
  type EmailMatterFilingDto,
  type EmailMatterSuggestionDto,
  type EmailMatterSuggestionListDto,
  type EmailMatterSuggestionQueryDto,
  type EmailMatterWarningCode,
  type EmailPrivilegeSuggestionReasonCode,
  type EmailPrivilegeTagSuggestion,
  type EmailPrivilegeTagSuggestionDto,
  type EmailThreadSummaryDto,
  type EmailTimelineDto,
  type EmailFailureReasonCode,
  type EmailMessageDto,
  type EmailParserKind,
  type EmailParseStatus,
  type FileEmailToMatterDto,
  type UploadEmailToMatterFieldsDto,
  type UploadEmailToMatterResponseDto,
} from './email/email-types';
export {
  acquireOutlookGraphAttachmentSchema,
  cancelOutlookFilingRequestSchema,
  createOutlookDocumentInsertionSchema,
  createOutlookEmailFilingRequestSchema,
  createOutlookFolderMappingSchema,
  createOutlookSendFileRequestSchema,
  evaluateOutlookSendPolicySchema,
  matterSuggestionQuerySchema,
  matterSuggestionReasonCodes,
  outlookAddinSessionExchangeSchema,
  outlookAddinSessionStatuses,
  outlookAttachmentRefSchema,
  outlookAutofileDeniedReasonCodes,
  outlookAutofileJobStatuses,
  outlookDeniedReasonCodes,
  outlookDocumentInsertionDeniedReasonCodes,
  outlookDocumentInsertionModes,
  outlookDocumentInsertionStatuses,
  outlookFolderMappingApprovalDecisions,
  outlookFolderMappingApprovalStatuses,
  outlookFolderMappingDeniedReasonCodes,
  outlookFolderMappingModes,
  outlookFilingRequestKinds,
  outlookFilingRequestStatuses,
  outlookGraphAttachmentAcquisitionStatuses,
  outlookHashSchema,
  outlookItemRefSchema,
  outlookMailboxBindingStatuses,
  outlookSendPolicyDecisions,
  outlookSendWarningReasonCodes,
  outlookSourceClients,
  updateOutlookFolderMappingSchema,
  type AcquireOutlookGraphAttachmentDto,
  type CancelOutlookFilingRequestDto,
  type CreateOutlookDocumentInsertionDto,
  type CreateOutlookEmailFilingRequestDto,
  type CreateOutlookFolderMappingDto,
  type CreateOutlookSendFileRequestDto,
  type EvaluateOutlookSendPolicyDto,
  type MatterSuggestionDto,
  type MatterSuggestionListDto,
  type MatterSuggestionQueryDto,
  type MatterSuggestionReasonCode,
  type OutlookAddinSessionDto,
  type OutlookAddinSessionExchangeDto,
  type OutlookAddinSessionStatus,
  type OutlookAttachmentRefDto,
  type OutlookAutofileDeniedReasonCode,
  type OutlookAutofileJobDto,
  type OutlookAutofileJobStatus,
  type OutlookDeniedReasonCode,
  type OutlookDocumentInsertionDeniedReasonCode,
  type OutlookDocumentInsertionDto,
  type OutlookDocumentInsertionMode,
  type OutlookDocumentInsertionStatus,
  type OutlookFolderMappingApprovalDecision,
  type OutlookFolderMappingApprovalStatus,
  type OutlookFolderMappingDeniedReasonCode,
  type OutlookFolderMappingDto,
  type OutlookFolderMappingMode,
  type OutlookFilingRequestKind,
  type OutlookFilingRequestStatus,
  type OutlookFilingRequestStatusDto,
  type OutlookGraphAttachmentAcquisitionDto,
  type OutlookGraphAttachmentAcquisitionStatus,
  type OutlookIntegrationAdminEvidenceKind,
  type OutlookIntegrationAdminEvidenceStatusDto,
  type OutlookIntegrationAdminFeature,
  type OutlookIntegrationAdminFeatureStatusDto,
  type OutlookIntegrationAdminRing,
  type OutlookIntegrationAdminStatusDto,
  type OutlookItemRefDto,
  type OutlookMailboxBindingStatus,
  type OutlookSendFileRequestStatusDto,
  type OutlookSendPolicyDecision,
  type OutlookSendPolicyDecisionDto,
  type OutlookSendWarningReasonCode,
  type OutlookSourceClient,
  type UpdateOutlookFolderMappingDto,
} from './outlook/outlook-types';
export {
  outlookApprovedGraphScopeRegistry,
  outlookApprovedScopeNames,
  outlookApprovedScopeSetHashSource,
  outlookGraphConsentKinds,
  outlookGraphScopePurposes,
  outlookRejectedGraphScopes,
  type OutlookGraphConsentKind,
  type OutlookGraphScopePurpose,
  type OutlookGraphScopeRegistryEntry,
} from './outlook/outlook-graph-scopes';
export {
  emailMetadataWarningCodes,
  emailParticipantRoles,
  normalizeEmailMetadata,
  type EmailMetadataWarningCode,
  type EmailParticipantRole,
  type NormalizedEmailMetadata,
  type NormalizedEmailParticipant,
} from './email/email-metadata';
export {
  EmlParseError,
  parseEmlHeaders,
  parseEmlEnvelope,
  type EmlParseFailureReason,
  type ParsedEmlHeader,
  type ParsedEmlEnvelope,
} from './email/eml-parser';
export {
  canIssueSessionForRole,
  isUserRole,
  userRoles,
  userRoleSchema,
  type UserRole,
} from './permission/roles';
export {
  isRolePermissionAction,
  rolePermissionActions,
  rolePermissionActionSchema,
  type RolePermissionAction,
} from './permission/permission-actions';
export {
  assertCompleteRolePermissionMatrix,
  isRoleAllowedForAction,
  rolePermissionDecision,
  rolePermissionMatrix,
  type RolePermissionDecision,
  type RolePermissionMatrix,
} from './permission/role-permission-matrix';
export {
  allowPermission,
  denyPermission,
  type PermissionDecision,
  type PermissionEffect,
  type PermissionReasonCode,
} from './permission/permission-decision';
export {
  evaluatePermissionCondition,
  permissionAttributeKeys,
  permissionConditionOperators,
  type PermissionAttributeContext,
  type PermissionAttributeKey,
  type PermissionAttributeValue,
  type PermissionConditionEvaluation,
  type PermissionConditionEvaluationOutcome,
  type PermissionConditionOperator,
} from './permission/attribute-policy';
export type {
  DocumentPermissionService,
  PermissionContext,
} from './permission/document-permission.interface';
export { assignUserRoleSchema, type AssignUserRoleDto } from './user/user-role.dto';
export type {
  CurrentUserResponseDto,
  LoginRequestDto,
  LoginResponseDto,
  PasswordResetAcceptedDto,
  PasswordResetConfirmDto,
  PasswordResetRequestDto,
} from './dto/auth.dto';
export type { TenantSettingsDto } from './dto/tenant-settings.dto';
export {
  uploadDocumentFieldsSchema,
  type DocumentMetadataSuggestionDto,
  type UploadDocumentFieldsDto,
  type UploadDocumentResponseDto,
} from './dto/document/upload-document.dto';
export {
  addDocumentVersionFieldsSchema,
  type AddDocumentVersionFieldsDto,
  type AddDocumentVersionResponseDto,
} from './dto/document/add-version.dto';
export {
  documentVersionStatusSchema,
  documentVersionStatuses,
  listDocumentVersionsQuerySchema,
  type DocumentVersionDto,
  type DocumentVersionListDto,
  type DocumentVersionStatus,
  type ListDocumentVersionsQueryDto,
} from './dto/document/version-list.dto';
export {
  updateDocumentMetadataSchema,
  type UpdateDocumentMetadataDto,
} from './dto/document/update-document-metadata.dto';
export {
  documentDownloadReasonCodes,
  documentDownloadReasonCodeSchema,
  documentDownloadReasonQuerySchema,
  type DocumentDownloadReasonCode,
  type DocumentDownloadReasonQueryDto,
} from './dto/document/download-reason.dto';
export { updateLegalHoldSchema, type UpdateLegalHoldDto } from './dto/legal-hold.dto';
export {
  bulkUploadFileSchema,
  bulkUploadJobItemSchema,
  bulkUploadJobSchema,
  bulkUploadQueueName,
  type BulkUploadFailedItemDto,
  type BulkUploadItemResultDto,
  type BulkUploadJobDto,
  type BulkUploadJobItemDto,
  type BulkUploadReportDto,
  type BulkUploadSuccessItemDto,
} from './dto/document/bulk-upload.dto';
export {
  auditExportQuerySchema,
  auditQueryActionSchema,
  auditQuerySchema,
  auditResultSchema,
  auditTargetTypeSchema,
  documentAuditQueryEventTypeSchema,
  documentAuditQuerySchema,
  matterAuditQuerySchema,
  type AuditEventDto,
  type AuditEventListDto,
  type AuditExportQueryDto,
  type AuditExportResultDto,
  type AuditQueryDto,
  type DocumentAuditEventDto,
  type DocumentAuditEventListDto,
  type DocumentAuditQueryDto,
  type DocumentAuditQueryEventType,
  type MatterAuditQueryDto,
} from './dto/audit/audit-query.dto';
export {
  createSavedSearchSchema,
  searchDocumentTypeFilterSchema,
  searchFiltersSchema,
  searchIsoDateTimeSchema,
  searchGroupBySchema,
  searchGroupBys,
  searchModeSchema,
  searchModes,
  searchQuerySchema,
  searchSortSchema,
  searchSorts,
  searchTargetSchema,
  searchTargets,
  searchVersionStatusSchema,
  searchVersionStatusValues,
  type CreateSavedSearchDto,
  type SavedSearchDto,
  type SavedSearchListDto,
  type SearchDateRangeFacetDto,
  type SearchDocumentTypeFilterDto,
  type SearchFacetBucketDto,
  type SearchFacetsDto,
  type SearchFiltersDto,
  type SearchGroupBy,
  type SearchHighlightDto,
  type SearchMode,
  type SearchQueryDto,
  type SearchResponseDto,
  type SearchResultDto,
  type SearchSort,
  type SearchTarget,
  type SearchVersionStatus,
} from './search/search-query.dto';
export {
  aiChunkKindSchema,
  aiChunkKinds,
  aiEmbeddingDimension,
  documentChunkProvenanceSchema,
  type AiChunkKind,
  type DocumentChunkProvenanceDto,
} from './ai/chunk';
export {
  evidencePackChunkSchema,
  evidencePackGraphFactSchema,
  evidencePackRuleFindingSchema,
  evidencePackSchema,
  evidencePackSourceTypeSchema,
  evidencePackTaskTypeSchema,
  evidencePackTaskTypes,
  evidencePackV2PrepAdapterSchema,
  evidencePackV2PrepSourceRefEntrySchema,
  adaptEvidencePackToPrepSourceRefs,
  type EvidencePackChunkDto,
  type EvidencePackDto,
  type EvidencePackGraphFactDto,
  type EvidencePackRuleFindingDto,
  type EvidencePackTaskType,
  type EvidencePackV2PrepAdapterDto,
  type EvidencePackV2PrepSourceRefEntryDto,
} from './ai/evidence-pack';
export {
  graphConsistencyDriftSchema,
  graphConsistencyResponseSchema,
  graphEdgeTypeSchema,
  graphEdgeTypes,
  graphFactSchema,
  graphFactsQuerySchema,
  graphFactsResponseSchema,
  graphNodeRefSchema,
  graphNodeTypeSchema,
  graphNodeTypes,
  graphSyncRequestSchema,
  graphSyncResponseSchema,
  type GraphConsistencyDriftDto,
  type GraphConsistencyResponseDto,
  type GraphEdgeType,
  type GraphFactDto,
  type GraphFactsQueryDto,
  type GraphFactsResponseDto,
  type GraphNodeType,
  type GraphSyncRequestDto,
  type GraphSyncResponseDto,
} from './graph/graph-types';
export {
  contractClassificationSchema,
  contractClauseKindSchema,
  contractClauseKinds,
  contractClauseBankItemSchema,
  contractClauseBankQuerySchema,
  contractClauseBankResponseSchema,
  contractProcessRequestSchema,
  contractProcessResponseSchema,
  contractRuleFindingSchema,
  contractRuleFindingsQuerySchema,
  contractRuleFindingsResponseSchema,
  contractRuleFindingStatusSchema,
  contractTypeSchema,
  contractTypes,
  createPlaybookRuleRequestSchema,
  playbookRuleResponseSchema,
  playbookRuleSeveritySchema,
  playbookRuleTypeSchema,
  playbookRuleTypes,
  redlineChangeTypeSchema,
  redlineChangeTypes,
  type ContractClauseBankItemDto,
  type ContractClauseBankQueryDto,
  type ContractClauseBankResponseDto,
  type ContractClassificationDto,
  type ContractClauseKind,
  type ContractProcessRequestDto,
  type ContractProcessResponseDto,
  type ContractRuleFindingDto,
  type ContractRuleFindingStatus,
  type ContractRuleFindingsQueryDto,
  type ContractRuleFindingsResponseDto,
  type ContractType,
  type CreatePlaybookRuleRequestDto,
  type PlaybookRuleResponseDto,
  type PlaybookRuleSeverity,
  type PlaybookRuleType,
  type RedlineChangeType,
} from './contract/contract-types';
export {
  aiModelRouteSchema,
  aiModelTierSchema,
  aiRoutingDecisionSchema,
  aiRoutingEffectSchema,
  aiTaskKindSchema,
  aiTaskRiskSchema,
  type AiModelRoute,
  type AiRoutingDecisionDto,
  type AiRoutingEffect,
  type AiTaskKind,
  type AiTaskRisk,
} from './ai/model-routing';
export {
  aiCitationClaimSchema,
  aiCitationSchema,
  aiCitationSourceRequestSchema,
  aiCitationSourceResponseSchema,
  aiCitationSourceSchema,
  aiCitationVerificationRequestSchema,
  aiCitationVerificationResponseSchema,
  aiCitationVerificationWarningSchema,
  aiCitationWarningCodeSchema,
  type AiCitationClaimDto,
  type AiCitationDto,
  type AiCitationSourceDto,
  type AiCitationSourceRequestDto,
  type AiCitationSourceResponseDto,
  type AiCitationVerificationRequestDto,
  type AiCitationVerificationResponseDto,
  type AiCitationVerificationWarningDto,
  type AiCitationWarningCode,
} from './ai/citation';
export {
  aiGroundedClaimKindSchema,
  aiGroundedClaimSchema,
  aiGroundedGenerationOutputSchema,
  aiGroundedSectionSchema,
  aiGroundedSourceRefSchema,
  type AiGroundedClaimDto,
  type AiGroundedClaimKind,
  type AiGroundedGenerationOutputDto,
  type AiGroundedSectionDto,
} from './ai/generation';
export {
  aiPrepArtifactKinds,
  aiPrepArtifactAllowedClaimKinds,
  aiPrepArtifactClaimKindAllowlist,
  aiPrepArtifactKindSchema,
  aiPrepArtifactPayloadForKindSchema,
  aiPrepArtifactPayloadSchema,
  aiPrepArtifactSummarySchema,
  aiPrepClaimKinds,
  aiPrepClaimKindSchema,
  aiPrepDocumentReadinessStatuses,
  aiPrepDocumentReadinessStatusSchema,
  aiPrepDocumentStatusSchema,
  aiPrepFeedbackKinds,
  aiPrepFeedbackKindSchema,
  aiPrepFeedbackReasonCodes,
  aiPrepFeedbackReasonCodeSchema,
  aiPrepFeedbackRequestSchema,
  aiPrepFeedbackResponseSchema,
  aiPrepMatterDocumentReadinessSchema,
  aiPrepMatterReadinessSchema,
  aiPrepMatterRetryResponseSchema,
  aiPrepPayloadBannedTopLevelKeys,
  aiPrepGroundedGenerationOutputSchema,
  parseAiPrepArtifactPayload,
  aiPrepStaleReasons,
  aiPrepStaleReasonSchema,
  aiPrepStatuses,
  aiPrepStatusSchema,
  type AiPrepArtifactKind,
  type AiPrepArtifactPayloadDto,
  type AiPrepArtifactSummaryDto,
  type AiPrepClaimKind,
  type AiPrepDocumentReadinessStatus,
  type AiPrepDocumentStatusDto,
  type AiPrepFeedbackKind,
  type AiPrepFeedbackReasonCode,
  type AiPrepFeedbackRequestDto,
  type AiPrepFeedbackResponseDto,
  type AiPrepMatterDocumentReadinessDto,
  type AiPrepMatterReadinessDto,
  type AiPrepMatterRetryResponseDto,
  type AiPrepStaleReason,
  type AiPrepStatus,
} from './ai/prep';
export {
  localAiEndpointClasses,
  localAiEndpointClassSchema,
  localAiEvalReportSchema,
  localAiOpsHealthSchema,
  localAiOpsMetricsSchema,
  localAiRuntimeStatuses,
  localAiRuntimeStatusSchema,
  type LocalAiEndpointClass,
  type LocalAiEvalReportDto,
  type LocalAiOpsHealthDto,
  type LocalAiOpsMetricsDto,
  type LocalAiRuntimeStatus,
} from './ai/ops';
export {
  aiSummaryRequestSchema,
  aiSummaryResponseSchema,
  aiSummarySectionSchema,
  aiSummaryStatusSchema,
  aiSummaryTaskSchema,
  aiSummaryWarningCodeSchema,
  type AiSummaryRequestDto,
  type AiSummaryResponseDto,
  type AiSummarySectionDto,
  type AiSummaryStatus,
  type AiSummaryTask,
  type AiSummaryWarningCode,
} from './ai/summary';
export {
  aiFeedbackCorrectionTypes,
  aiFeedbackErrorTypes,
  aiFeedbackMetricsSchema,
  aiFeedbackRequestSchema,
  aiFeedbackResponseSchema,
  type AiFeedbackCorrectionType,
  type AiFeedbackErrorType,
  type AiFeedbackMetricsDto,
  type AiFeedbackRequestDto,
  type AiFeedbackResponseDto,
} from './ai/feedback';
export {
  aiSessionChunkDetailSchema,
  aiSessionChunkLogSchema,
  aiSessionChunkReasonCodeSchema,
  aiSessionCreateSchema,
  aiSessionDetailSchema,
  aiSessionModelRouteSchema,
  aiSessionResponseLogSchema,
  aiSessionStatusSchema,
  type AiSessionChunkDetailDto,
  type AiSessionChunkLogDto,
  type AiSessionChunkReasonCode,
  type AiSessionCreateDto,
  type AiSessionDetailDto,
  type AiSessionModelRoute,
  type AiSessionResponseLogDto,
  type AiSessionStatus,
} from './ai/session';

export {
  clientConfidentialityLevels,
  clientConfidentialityLevelSchema,
  clientStatuses,
  clientStatusSchema,
  clientTypes,
  clientTypeSchema,
  type ClientConfidentialityLevel,
  type ClientStatus,
  type ClientType,
} from './client/client-enums';
export {
  createClientSchema,
  listClientsQuerySchema,
  updateClientSchema,
  type ClientDto,
  type ClientListDto,
  type CreateClientDto,
  type ListClientsQueryDto,
  type UpdateClientDto,
} from './client/client.dto';
export { matterTypes, matterTypeSchema, type MatterType } from './matter/matter-type';
export {
  containsSensitiveMatterMetadataKey,
  isMatterDateRangeValid,
  matterMetadataSchema,
  matterOptionalDateSchema,
} from './matter/matter-validation';
export {
  createMatterSchema,
  listMattersQuerySchema,
  matterStatuses,
  matterStatusSchema,
  updateMatterSchema,
  updateMatterStatusSchema,
  type CreateMatterDto,
  type ListMattersQueryDto,
  type MatterDto,
  type MatterListDto,
  type MatterStatus,
  type UpdateMatterDto,
  type UpdateMatterStatusDto,
} from './matter/matter.dto';
export {
  addMatterMemberSchema,
  matterMemberAccessLevelSchema,
  matterMemberAccessLevels,
  matterMemberRoleSchema,
  matterMemberRoles,
  updateMatterMemberSchema,
  type AddMatterMemberDto,
  type MatterMemberAccessLevel,
  type MatterMemberDto,
  type MatterMemberListDto,
  type MatterMemberRole,
  type UpdateMatterMemberDto,
} from './matter/matter-member.dto';
export {
  ethicalWallMembershipInputSchema,
  createEthicalWallSchema,
  ethicalWallStatuses,
  listEthicalWallsQuerySchema,
  wallMembershipTypes,
  wallSubjectTypes,
  type AddEthicalWallMembershipDto,
  type CreateEthicalWallDto,
  type CreateEthicalWallMemberDto,
  type EthicalWallDetailDto,
  type EthicalWallDto,
  type EthicalWallListDto,
  type EthicalWallMembershipDto,
  type EthicalWallStatus,
  type ListEthicalWallsQueryDto,
  type WallMembershipType,
  type WallSubjectType,
} from './ethical-wall/ethical-wall.dto';
export {
  partyRoleSchema,
  partyRoles,
  partyTypeSchema,
  partyTypes,
  type PartyRole,
  type PartyType,
} from './party/party-enums';
export {
  createPartySchema,
  listPartiesQuerySchema,
  updatePartySchema,
  type CreatePartyDto,
  type ListPartiesQueryDto,
  type PartyDto,
  type PartyListDto,
  type UpdatePartyDto,
} from './party/party.dto';
