import { z } from 'zod';

export const ERROR_CODES = [
  'AUTH_REQUIRED',
  'PERMISSION_DENIED',
  'ETHICAL_WALL_BLOCKED',
  'AI_POLICY_BLOCKED',
  'DOCUMENT_LOCKED',
  'VALIDATION_FAILED',
  'UNSUPPORTED_FILE_TYPE',
  'EXTERNAL_LINK_EXPIRED',
  'TENANT_ISOLATION_VIOLATION',
] as const;

export type ErrorCode = (typeof ERROR_CODES)[number];

export const errorCodeSchema = z.enum(ERROR_CODES);

export interface ApiErrorResponse {
  code: ErrorCode;
  message?: string;
  requestId?: string;
}

export {
  auditActions,
  auditMetadataKeys,
  isAuditAction,
  isAuditMetadataKey,
  r1AuditActions,
  r2DocumentAuditActions,
  r3SearchAuditActions,
  r4DlpAuditActions,
  r4EmailAuditActions,
  r5AuditConsoleActions,
  r5BreakGlassAuditActions,
  r6AiAuditActions,
  r6AiFeedbackAuditActions,
  r6AiPolicyAuditActions,
  r7GraphAuditActions,
  r8ContractAuditActions,
  r9DdAuditActions,
  r10LitigationAuditActions,
  r11ExternalAuditActions,
  type AuditAction,
  type AuditMetadata,
  type AuditMetadataKey,
  type AuditMetadataValue,
  type R1AuditAction,
  type R2DocumentAuditAction,
  type R3SearchAuditAction,
  type R4DlpAuditAction,
  type R4EmailAuditAction,
  type R5AuditConsoleAction,
  type R5BreakGlassAuditAction,
  type R6AiAuditAction,
  type R6AiFeedbackAuditAction,
  type R6AiPolicyAuditAction,
  type R7GraphAuditAction,
  type R8ContractAuditAction,
  type R9DdAuditAction,
  type R10LitigationAuditAction,
  type R11ExternalAuditAction,
} from './types/audit';
export {
  createDdDataRoomMappingRequestSchema,
  createDdIssueRequestSchema,
  createDdRfiRequestSchema,
  createDdRiskRequestSchema,
  ddDataRoomMappingListResponseSchema,
  ddDataRoomMappingQuerySchema,
  ddDataRoomMappingSchema,
  ddIssueListResponseSchema,
  ddIssueQuerySchema,
  ddIssueSchema,
  ddIssueSeveritySchema,
  ddIssueStatusSchema,
  ddIssueSeverities,
  ddIssueStatuses,
  ddMappingStatusSchema,
  ddMappingStatuses,
  ddPriorities,
  ddPrioritySchema,
  ddRfiCategories,
  ddRfiCategorySchema,
  ddRfiListResponseSchema,
  ddRfiQuerySchema,
  ddRfiSchema,
  ddRfiStatusSchema,
  ddRfiStatuses,
  ddRiskCategories,
  ddRiskCategorySchema,
  ddRiskLikelihoodSchema,
  ddRiskLikelihoods,
  ddRiskListResponseSchema,
  ddRiskQuerySchema,
  ddRiskSchema,
  ddRiskStatusSchema,
  ddRiskStatuses,
  ddTraceabilityQuerySchema,
  ddTraceabilityResponseSchema,
  ddTraceabilityItemSchema,
  updateDdRfiRequestSchema,
  type CreateDdDataRoomMappingRequestDto,
  type CreateDdIssueRequestDto,
  type CreateDdRfiRequestDto,
  type CreateDdRiskRequestDto,
  type DdDataRoomMappingDto,
  type DdDataRoomMappingListResponseDto,
  type DdDataRoomMappingQueryDto,
  type DdIssueDto,
  type DdIssueListResponseDto,
  type DdIssueQueryDto,
  type DdIssueSeverity,
  type DdIssueStatus,
  type DdMappingStatus,
  type DdPriority,
  type DdRfiCategory,
  type DdRfiDto,
  type DdRfiListResponseDto,
  type DdRfiQueryDto,
  type DdRfiStatus,
  type DdRiskCategory,
  type DdRiskDto,
  type DdRiskLikelihood,
  type DdRiskListResponseDto,
  type DdRiskQueryDto,
  type DdRiskStatus,
  type DdTraceabilityItemDto,
  type DdTraceabilityQueryDto,
  type DdTraceabilityResponseDto,
  type UpdateDdRfiRequestDto,
} from './dd/dd-types';

export {
  createLitigationEvidenceRequestSchema,
  createLitigationFactRequestSchema,
  createLitigationIssueRequestSchema,
  createLitigationPleadingRequestSchema,
  litigationAdmittedStatusSchema,
  litigationAdmittedStatuses,
  litigationCaseMapItemSchema,
  litigationCaseMapQuerySchema,
  litigationCaseMapResponseSchema,
  litigationCustodyStatusSchema,
  litigationCustodyStatuses,
  litigationEvidenceListResponseSchema,
  litigationEvidenceQuerySchema,
  litigationEvidenceSchema,
  litigationEvidenceTypeSchema,
  litigationEvidenceTypes,
  litigationFactListResponseSchema,
  litigationFactQuerySchema,
  litigationFactSchema,
  litigationFactStatusSchema,
  litigationFactStatuses,
  litigationIssueListResponseSchema,
  litigationIssueQuerySchema,
  litigationIssueSchema,
  litigationIssueStatusSchema,
  litigationIssueStatuses,
  litigationIssueTypeSchema,
  litigationIssueTypes,
  litigationMaterialities,
  litigationMaterialitySchema,
  litigationPleadingListResponseSchema,
  litigationPleadingQuerySchema,
  litigationPleadingSchema,
  litigationPleadingStatusSchema,
  litigationPleadingStatuses,
  litigationPleadingTypeSchema,
  litigationPleadingTypes,
  type CreateLitigationEvidenceRequestDto,
  type CreateLitigationFactRequestDto,
  type CreateLitigationIssueRequestDto,
  type CreateLitigationPleadingRequestDto,
  type LitigationAdmittedStatus,
  type LitigationCaseMapItemDto,
  type LitigationCaseMapQueryDto,
  type LitigationCaseMapResponseDto,
  type LitigationCustodyStatus,
  type LitigationEvidenceDto,
  type LitigationEvidenceListResponseDto,
  type LitigationEvidenceQueryDto,
  type LitigationEvidenceType,
  type LitigationFactDto,
  type LitigationFactListResponseDto,
  type LitigationFactQueryDto,
  type LitigationFactStatus,
  type LitigationIssueDto,
  type LitigationIssueListResponseDto,
  type LitigationIssueQueryDto,
  type LitigationIssueStatus,
  type LitigationIssueType,
  type LitigationMateriality,
  type LitigationPleadingDto,
  type LitigationPleadingListResponseDto,
  type LitigationPleadingQueryDto,
  type LitigationPleadingStatus,
  type LitigationPleadingType,
} from './litigation/litigation-types';

export {
  acceptExternalNdaRequestSchema,
  createExternalLinkRequestSchema,
  createExternalUserRequestSchema,
  createExternalWorkspaceRequestSchema,
  externalAccessManifestSchema,
  externalAccessStatusResponseSchema,
  externalAccessStatusSchema,
  externalAccessStatuses,
  externalLinkCreatedResponseSchema,
  externalLinkSchema,
  externalLinkStatusSchema,
  externalLinkStatuses,
  externalNdaAcceptanceSchema,
  externalUserSchema,
  externalUserStatusSchema,
  externalUserStatuses,
  externalWorkspaceSchema,
  externalWorkspaceStatusSchema,
  externalWorkspaceStatuses,
  type AcceptExternalNdaRequestDto,
  type CreateExternalLinkRequestDto,
  type CreateExternalUserRequestDto,
  type CreateExternalWorkspaceRequestDto,
  type ExternalAccessManifestDto,
  type ExternalAccessStatus,
  type ExternalAccessStatusResponseDto,
  type ExternalLinkCreatedResponseDto,
  type ExternalLinkDto,
  type ExternalLinkStatus,
  type ExternalNdaAcceptanceDto,
  type ExternalUserDto,
  type ExternalUserStatus,
  type ExternalWorkspaceDto,
  type ExternalWorkspaceStatus,
} from './external/external-types';

export {
  aiModelRouteKeys,
  aiModelTiers,
  aiPolicyBlockReasonCodes,
  aiPolicyBlockedResponse,
  aiPolicyPurposes,
  type AiDocumentPolicyDecision,
  type AiModelRouteKey,
  type AiModelTier,
  type AiPolicyAuditResult,
  type AiPolicyBlockReasonCode,
  type AiPolicyBlockedResponse,
  type AiPolicyDecisionEffect,
  type AiPolicyDefaultEffect,
  type AiPolicyEvaluationRequest,
  type AiPolicyEvaluationResult,
  type AiPolicyPurpose,
  type AiPolicySchema,
} from './types/ai-policy';
export {
  breakGlassReasonCodes,
  breakGlassRequestStatuses,
  createBreakGlassRequestSchema,
  revokeBreakGlassRequestSchema,
  type BreakGlassReasonCode,
  type BreakGlassRequestDto,
  type BreakGlassRequestStatus,
  type CreateBreakGlassRequestDto,
  type RevokeBreakGlassRequestDto,
} from './break-glass/break-glass.dto';

export {
  tenantStatuses,
  workspaceStatuses,
  type TenantId,
  type TenantStatus,
  type TenantSummary,
  type WorkspaceStatus,
} from './types/tenant';
export { userStatuses, type UserStatus, type UserSummary } from './types/user';
export type { FileObjectDto } from './types/file-object';
export {
  documentConfidentialityLevelSchema,
  documentConfidentialityLevels,
  documentPrivilegeStatusSchema,
  documentPrivilegeStatuses,
  documentExtractionMethods,
  documentExtractionStatuses,
  documentStatusSchema,
  documentStatuses,
  documentTypeSchema,
  documentTypes,
  type DocumentConfidentialityLevel,
  type DocumentDto,
  type DocumentExtractionMethod,
  type DocumentExtractionStatus,
  type DocumentPrivilegeStatus,
  type DocumentStatus,
  type DocumentType,
} from './types/document';
export {
  dlpFindingTypes,
  dlpRuleIds,
  type DlpDetection,
  type DlpFindingType,
  type DlpRuleId,
  type DlpScanOptions,
} from './dlp/dlp-types';
export {
  emailFailureReasonCodes,
  emailMatterWarningCodes,
  emailMatterSuggestionQuerySchema,
  emailPrivilegeSuggestionReasonCodes,
  emailPrivilegeTagSuggestions,
  emailParserKinds,
  emailParseStatuses,
  fileEmailToMatterSchema,
  uploadEmailToMatterFieldsSchema,
  type EmailMatterFilingDto,
  type EmailMatterSuggestionDto,
  type EmailMatterSuggestionListDto,
  type EmailMatterSuggestionQueryDto,
  type EmailMatterWarningCode,
  type EmailPrivilegeSuggestionReasonCode,
  type EmailPrivilegeTagSuggestion,
  type EmailPrivilegeTagSuggestionDto,
  type EmailThreadSummaryDto,
  type EmailTimelineDto,
  type EmailFailureReasonCode,
  type EmailMessageDto,
  type EmailParserKind,
  type EmailParseStatus,
  type FileEmailToMatterDto,
  type UploadEmailToMatterFieldsDto,
  type UploadEmailToMatterResponseDto,
} from './email/email-types';
export {
  emailMetadataWarningCodes,
  emailParticipantRoles,
  normalizeEmailMetadata,
  type EmailMetadataWarningCode,
  type EmailParticipantRole,
  type NormalizedEmailMetadata,
  type NormalizedEmailParticipant,
} from './email/email-metadata';
export {
  EmlParseError,
  parseEmlHeaders,
  parseEmlEnvelope,
  type EmlParseFailureReason,
  type ParsedEmlHeader,
  type ParsedEmlEnvelope,
} from './email/eml-parser';
export {
  canIssueSessionForRole,
  isUserRole,
  userRoles,
  userRoleSchema,
  type UserRole,
} from './permission/roles';
export {
  isRolePermissionAction,
  rolePermissionActions,
  rolePermissionActionSchema,
  type RolePermissionAction,
} from './permission/permission-actions';
export {
  assertCompleteRolePermissionMatrix,
  isRoleAllowedForAction,
  rolePermissionDecision,
  rolePermissionMatrix,
  type RolePermissionDecision,
  type RolePermissionMatrix,
} from './permission/role-permission-matrix';
export {
  allowPermission,
  denyPermission,
  type PermissionDecision,
  type PermissionEffect,
  type PermissionReasonCode,
} from './permission/permission-decision';
export {
  evaluatePermissionCondition,
  permissionAttributeKeys,
  permissionConditionOperators,
  type PermissionAttributeContext,
  type PermissionAttributeKey,
  type PermissionAttributeValue,
  type PermissionConditionEvaluation,
  type PermissionConditionEvaluationOutcome,
  type PermissionConditionOperator,
} from './permission/attribute-policy';
export type {
  DocumentPermissionService,
  PermissionContext,
} from './permission/document-permission.interface';
export { assignUserRoleSchema, type AssignUserRoleDto } from './user/user-role.dto';
export type {
  LoginRequestDto,
  LoginResponseDto,
  PasswordResetAcceptedDto,
  PasswordResetConfirmDto,
  PasswordResetRequestDto,
} from './dto/auth.dto';
export type { TenantSettingsDto } from './dto/tenant-settings.dto';
export {
  uploadDocumentFieldsSchema,
  type DocumentMetadataSuggestionDto,
  type UploadDocumentFieldsDto,
  type UploadDocumentResponseDto,
} from './dto/document/upload-document.dto';
export {
  addDocumentVersionFieldsSchema,
  type AddDocumentVersionFieldsDto,
  type AddDocumentVersionResponseDto,
} from './dto/document/add-version.dto';
export {
  documentVersionStatusSchema,
  documentVersionStatuses,
  listDocumentVersionsQuerySchema,
  type DocumentVersionDto,
  type DocumentVersionListDto,
  type DocumentVersionStatus,
  type ListDocumentVersionsQueryDto,
} from './dto/document/version-list.dto';
export {
  updateDocumentMetadataSchema,
  type UpdateDocumentMetadataDto,
} from './dto/document/update-document-metadata.dto';
export {
  documentDownloadReasonCodes,
  documentDownloadReasonCodeSchema,
  documentDownloadReasonQuerySchema,
  type DocumentDownloadReasonCode,
  type DocumentDownloadReasonQueryDto,
} from './dto/document/download-reason.dto';
export { updateLegalHoldSchema, type UpdateLegalHoldDto } from './dto/legal-hold.dto';
export {
  bulkUploadFileSchema,
  bulkUploadJobItemSchema,
  bulkUploadJobSchema,
  bulkUploadQueueName,
  type BulkUploadFailedItemDto,
  type BulkUploadItemResultDto,
  type BulkUploadJobDto,
  type BulkUploadJobItemDto,
  type BulkUploadReportDto,
  type BulkUploadSuccessItemDto,
} from './dto/document/bulk-upload.dto';
export {
  auditExportQuerySchema,
  auditQueryActionSchema,
  auditQuerySchema,
  auditResultSchema,
  auditTargetTypeSchema,
  documentAuditQueryEventTypeSchema,
  documentAuditQuerySchema,
  type AuditEventDto,
  type AuditEventListDto,
  type AuditExportQueryDto,
  type AuditExportResultDto,
  type AuditQueryDto,
  type DocumentAuditEventDto,
  type DocumentAuditEventListDto,
  type DocumentAuditQueryDto,
  type DocumentAuditQueryEventType,
} from './dto/audit/audit-query.dto';
export {
  searchDocumentTypeFilterSchema,
  searchFiltersSchema,
  searchIsoDateTimeSchema,
  searchModeSchema,
  searchModes,
  searchQuerySchema,
  searchVersionStatusSchema,
  searchVersionStatusValues,
  type SearchDateRangeFacetDto,
  type SearchDocumentTypeFilterDto,
  type SearchFacetBucketDto,
  type SearchFacetsDto,
  type SearchFiltersDto,
  type SearchHighlightDto,
  type SearchMode,
  type SearchQueryDto,
  type SearchResponseDto,
  type SearchResultDto,
  type SearchVersionStatus,
} from './search/search-query.dto';
export {
  aiChunkKindSchema,
  aiChunkKinds,
  aiEmbeddingDimension,
  documentChunkProvenanceSchema,
  type AiChunkKind,
  type DocumentChunkProvenanceDto,
} from './ai/chunk';
export {
  evidencePackChunkSchema,
  evidencePackGraphFactSchema,
  evidencePackRuleFindingSchema,
  evidencePackSchema,
  evidencePackSourceTypeSchema,
  evidencePackTaskTypeSchema,
  evidencePackTaskTypes,
  type EvidencePackChunkDto,
  type EvidencePackDto,
  type EvidencePackGraphFactDto,
  type EvidencePackRuleFindingDto,
  type EvidencePackTaskType,
} from './ai/evidence-pack';
export {
  graphConsistencyDriftSchema,
  graphConsistencyResponseSchema,
  graphEdgeTypeSchema,
  graphEdgeTypes,
  graphFactSchema,
  graphFactsQuerySchema,
  graphFactsResponseSchema,
  graphNodeRefSchema,
  graphNodeTypeSchema,
  graphNodeTypes,
  graphSyncRequestSchema,
  graphSyncResponseSchema,
  type GraphConsistencyDriftDto,
  type GraphConsistencyResponseDto,
  type GraphEdgeType,
  type GraphFactDto,
  type GraphFactsQueryDto,
  type GraphFactsResponseDto,
  type GraphNodeType,
  type GraphSyncRequestDto,
  type GraphSyncResponseDto,
} from './graph/graph-types';
export {
  contractClassificationSchema,
  contractClauseKindSchema,
  contractClauseKinds,
  contractClauseBankItemSchema,
  contractClauseBankQuerySchema,
  contractClauseBankResponseSchema,
  contractProcessRequestSchema,
  contractProcessResponseSchema,
  contractRuleFindingSchema,
  contractRuleFindingsQuerySchema,
  contractRuleFindingsResponseSchema,
  contractRuleFindingStatusSchema,
  contractTypeSchema,
  contractTypes,
  createPlaybookRuleRequestSchema,
  playbookRuleResponseSchema,
  playbookRuleSeveritySchema,
  playbookRuleTypeSchema,
  playbookRuleTypes,
  redlineChangeTypeSchema,
  redlineChangeTypes,
  type ContractClauseBankItemDto,
  type ContractClauseBankQueryDto,
  type ContractClauseBankResponseDto,
  type ContractClassificationDto,
  type ContractClauseKind,
  type ContractProcessRequestDto,
  type ContractProcessResponseDto,
  type ContractRuleFindingDto,
  type ContractRuleFindingStatus,
  type ContractRuleFindingsQueryDto,
  type ContractRuleFindingsResponseDto,
  type ContractType,
  type CreatePlaybookRuleRequestDto,
  type PlaybookRuleResponseDto,
  type PlaybookRuleSeverity,
  type PlaybookRuleType,
  type RedlineChangeType,
} from './contract/contract-types';
export {
  aiModelRouteSchema,
  aiModelTierSchema,
  aiRoutingDecisionSchema,
  aiRoutingEffectSchema,
  aiTaskKindSchema,
  aiTaskRiskSchema,
  type AiModelRoute,
  type AiRoutingDecisionDto,
  type AiRoutingEffect,
  type AiTaskKind,
  type AiTaskRisk,
} from './ai/model-routing';
export {
  aiCitationClaimSchema,
  aiCitationSchema,
  aiCitationSourceRequestSchema,
  aiCitationSourceResponseSchema,
  aiCitationSourceSchema,
  aiCitationVerificationRequestSchema,
  aiCitationVerificationResponseSchema,
  aiCitationVerificationWarningSchema,
  aiCitationWarningCodeSchema,
  type AiCitationClaimDto,
  type AiCitationDto,
  type AiCitationSourceDto,
  type AiCitationSourceRequestDto,
  type AiCitationSourceResponseDto,
  type AiCitationVerificationRequestDto,
  type AiCitationVerificationResponseDto,
  type AiCitationVerificationWarningDto,
  type AiCitationWarningCode,
} from './ai/citation';
export {
  aiSummaryRequestSchema,
  aiSummaryResponseSchema,
  aiSummarySectionSchema,
  aiSummaryStatusSchema,
  aiSummaryTaskSchema,
  aiSummaryWarningCodeSchema,
  type AiSummaryRequestDto,
  type AiSummaryResponseDto,
  type AiSummarySectionDto,
  type AiSummaryStatus,
  type AiSummaryTask,
  type AiSummaryWarningCode,
} from './ai/summary';
export {
  aiFeedbackCorrectionTypes,
  aiFeedbackErrorTypes,
  aiFeedbackMetricsSchema,
  aiFeedbackRequestSchema,
  aiFeedbackResponseSchema,
  type AiFeedbackCorrectionType,
  type AiFeedbackErrorType,
  type AiFeedbackMetricsDto,
  type AiFeedbackRequestDto,
  type AiFeedbackResponseDto,
} from './ai/feedback';
export {
  aiSessionChunkDetailSchema,
  aiSessionChunkLogSchema,
  aiSessionChunkReasonCodeSchema,
  aiSessionCreateSchema,
  aiSessionDetailSchema,
  aiSessionModelRouteSchema,
  aiSessionResponseLogSchema,
  aiSessionStatusSchema,
  type AiSessionChunkDetailDto,
  type AiSessionChunkLogDto,
  type AiSessionChunkReasonCode,
  type AiSessionCreateDto,
  type AiSessionDetailDto,
  type AiSessionModelRoute,
  type AiSessionResponseLogDto,
  type AiSessionStatus,
} from './ai/session';

export {
  clientConfidentialityLevels,
  clientConfidentialityLevelSchema,
  clientStatuses,
  clientStatusSchema,
  clientTypes,
  clientTypeSchema,
  type ClientConfidentialityLevel,
  type ClientStatus,
  type ClientType,
} from './client/client-enums';
export {
  createClientSchema,
  listClientsQuerySchema,
  updateClientSchema,
  type ClientDto,
  type ClientListDto,
  type CreateClientDto,
  type ListClientsQueryDto,
  type UpdateClientDto,
} from './client/client.dto';
export { matterTypes, matterTypeSchema, type MatterType } from './matter/matter-type';
export {
  containsSensitiveMatterMetadataKey,
  isMatterDateRangeValid,
  matterMetadataSchema,
  matterOptionalDateSchema,
} from './matter/matter-validation';
export {
  createMatterSchema,
  listMattersQuerySchema,
  matterStatuses,
  matterStatusSchema,
  updateMatterSchema,
  updateMatterStatusSchema,
  type CreateMatterDto,
  type ListMattersQueryDto,
  type MatterDto,
  type MatterListDto,
  type MatterStatus,
  type UpdateMatterDto,
  type UpdateMatterStatusDto,
} from './matter/matter.dto';
export {
  addMatterMemberSchema,
  matterMemberAccessLevelSchema,
  matterMemberAccessLevels,
  matterMemberRoleSchema,
  matterMemberRoles,
  updateMatterMemberSchema,
  type AddMatterMemberDto,
  type MatterMemberAccessLevel,
  type MatterMemberDto,
  type MatterMemberListDto,
  type MatterMemberRole,
  type UpdateMatterMemberDto,
} from './matter/matter-member.dto';
export {
  ethicalWallMembershipInputSchema,
  createEthicalWallSchema,
  ethicalWallStatuses,
  listEthicalWallsQuerySchema,
  wallMembershipTypes,
  wallSubjectTypes,
  type AddEthicalWallMembershipDto,
  type CreateEthicalWallDto,
  type CreateEthicalWallMemberDto,
  type EthicalWallDetailDto,
  type EthicalWallDto,
  type EthicalWallListDto,
  type EthicalWallMembershipDto,
  type EthicalWallStatus,
  type ListEthicalWallsQueryDto,
  type WallMembershipType,
  type WallSubjectType,
} from './ethical-wall/ethical-wall.dto';
export {
  partyRoleSchema,
  partyRoles,
  partyTypeSchema,
  partyTypes,
  type PartyRole,
  type PartyType,
} from './party/party-enums';
export {
  createPartySchema,
  listPartiesQuerySchema,
  updatePartySchema,
  type CreatePartyDto,
  type ListPartiesQueryDto,
  type PartyDto,
  type PartyListDto,
  type UpdatePartyDto,
} from './party/party.dto';
